format.h
=> Fix format using wostream produces wrong results

CMakeLists.txt
Currently you can't make install cppformat?
This fixes that
=> Add an install command to the cmake file (to allow make install)

doc/api.rst, doc/syntax.rst, format.cc, format.h, test/format-test.cc
=> Support named arguments

.gitignore
Title says it pretty much. I just love a clean submodule project status. Did I mention I like creating pull requests? :stuck_out_tongue_winking_eye:
=> add generated "run-msbuild.bat" file to gitignore

fmt/format.h
Hello!
I found that if I put custom type as a named argument it is impossible to get its size in variadic functions:
template < typename Char >
void serialize(Buffer &buffer, const fmt::internal::NamedArg< Char >& arg) {
// serialize named argument
}
So I extend fmt::internal::NamedArg with no overhead:
template < typename Char, typename T >
struct NamedArgWithType : NamedArg< Char > {
NamedArgWithType(BasicStringRef< Char > argname, const T &value)
: NamedArg< Char >(argname, value) {}
};
With this fix I was able to cover all args serializaton/deserializaton for base and trivially copyable types. 
Hope you'll accept this PR as well! Thanks in advance!
=> Introduced NamedArgWithType<Char, T> : NamedArg<Char>

fmt/posix.cc
=> Fix Windows compilation with -fno-exceptions

fmt/format.cc, fmt/printf.cc, test/add-subdirectory-test/main.cc, test/find-package-test/main.cc
=> Moved print() functions back to format.cc

fmt/ostream.h
This pull request adresses issue #484
=> fix for nvcc_wrapper compiler

CMakeLists.txt
=> Fixed CMake CMP0048 warning.

support/travis-build.py
=> Use less version to 2.6.1

fmt/format.h
=> Fix a bogus -Wduplicated-branches gcc warning (#573)

fmt/format.h
=> Workaround another MSVC constexpr bug

fmt/printf.h
=> Silenced MSVC 2017 constant if expression warning

include/fmt/printf.h
=> Add make_printf_args

fmt/format.h
This is a proposed fix for #707, for the 4.x branch.
=> Fix return that can't be reached

include/fmt/time.h
change total specialization of 'struct formatter<std::tm>' into partial specialization 'template <typename Char> struct formatter<std::tm, Char>', backed by matching 'strftime'-like overloads
=> allow time formatting with wchar_t contexts

include/fmt/format.h
=> Fix a -Wundef warning on clang

include/fmt/format.h
=> Fix compiler warning about narrowing

include/fmt/core.h, include/fmt/format-inl.h, include/fmt/format.h
=> remove trailing spaces.

include/fmt/printf.h
The iterator class itself and its helpers 'to_pointer' are removed after reformulating the formatting loop in terms of a 'basic_string_view<Char>::iterator'.
=> Get rid of 'null_terminating_iterator' in printf.h (#980)

include/fmt/format-inl.h
=> Fix warnings from Visual Studio

.github/pull_request_template.md
I don't know about the legal implications of this, just an idea.
And of course: I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.
=> Create PR template to help agree to the licensing terms

README.rst
=> Add MongoDB to "Projects using this library"

include/fmt/core.h, include/fmt/format-inl.h, include/fmt/format.h
Fixes #1186.  
Currently based on #1150.
=> Fix compilation issue on VS2019 (#1186)

include/fmt/format.h
=> Fix #1232.

README.rst
Added a nice shiny oss fuzz badge. The link appears to be wrong, but it isn't, there have been no bugs found by oss fuzz so far :-)
=> add oss fuzz badge

CMakeLists.txt
=> Fix shared build on Solaris

README.rst
=> let README point to python 3 instead of 2

include/fmt/core.h, test/core-test.cc
=> Fix handling of types convertible to std::string_view

include/fmt/format-inl.h, test/format-impl-test.cc
=> Initial implementation of square

include/fmt/color.h
After #1351 they became essentially the same.
=> Deduplicate color vformat and vprint

doc/usage.rst
=> [docs] Added conda

include/fmt/core.h, include/fmt/format.h, include/fmt/posix.h
=> Fix -Wconversion warnings

include/fmt/printf.h
=> Mitigate MSVC issue with min/max macros

include/fmt/format.h
=> check if _SECURE_SCL is defined not equal to 0

README.rst
=> Knuth is using fmt library

include/fmt/core.h
=> Spelling fixes

README.rst
I think it's good to have a link to a project with 10k+ stars.
It aligns perfectly with some other databases in the list.
Thank you for the great library!
=> Add ClickHouse to the list of projects

CMakeLists.txt
=> CMakeLists.txt: Added Wundef warning to clang and gcc.

include/fmt/os.h
=> Add append mode.

include/fmt/format-inl.h
Related to https://github.com/fmtlib/fmt/pull/1729. Details on https://github.com/gabime/spdlog/issues/1663.
=> NOMINMAX not handled properly

include/fmt/format.h
See https://github.com/fmtlib/fmt/issues/1426#issuecomment-694920646
=> Fix msvc version of clz & clzll

README.rst
I make extensive use of this library for building qkw targeting linux users. Please add this to your list.
https://github.com/ravijanjam/qkw
=> qkw: generalizing aliasing | using fmt library and it's features

include/fmt/format-inl.h
=> Simplify windows handling

include/fmt/core.h
=> Workaround a bug in gcc 7.5 (#1912)

doc/usage.rst
Just a documentation update since not everyone who may come across this library would be familiar with all the CMAKE variables.
=> added position independent documentation

include/fmt/format.h
=> Fixed format.h(1465): warning C4702: unreachable code

include/fmt/chrono.h
=> fix #2118: FMT_COMPILE did not work with tm formatter

include/fmt/os.h, src/os.cc, test/gtest-extra-test.cc, test/os-test.cc, test/posix-mock-test.cc
Discussion: https://github.com/fmtlib/fmt/issues/2266#issuecomment-835353462
=> Replace fmt::error_code to std::error_code

include/fmt/os.h
Some functionality is also required by `gtest_extra`
=> Export os.h API from a module

README.rst
=> Improves README with svg badge

include/fmt/core.h
=> Workaround to MSVC bug (#2474)

include/fmt/core.h
_MSC_VER 1911 (Visual Studio 2017 15.3)
=> Workaround for #2478

include/fmt/core.h, include/fmt/format.h
Fix for https://github.com/fmtlib/fmt/pull/2525#issuecomment-932793298 , https://gcc.godbolt.org/z/WPjG8fj4E
=> Move size_ initialization to initializer list

doc/build.py
See Sphinx issue: https://github.com/sphinx-doc/sphinx/issues/9777
=> Fix incompatible between docutils 1.18.0 and sphinx 3.3.0

include/fmt/core.h, include/fmt/format.h
resolves https://github.com/fmtlib/fmt/issues/2627
=> marks grow as FMT_CONSTEXPR20

test/CMakeLists.txt, test/gtest/CMakeLists.txt
Originated from https://github.com/fmtlib/fmt/pull/2256#issuecomment-828842031.
Just refactoring of existing code. Shouldn't break anything.
=> Testing improvements

include/fmt/core.h
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Remove two expressions which had no effect (reported by LGTM)

include/fmt/chrono.h
Fix for issue #2670 (Incorrect use of SFINAE).
=> Fix issue #2670

include/fmt/ranges.h
Issue https://github.com/fmtlib/fmt/issues/2754
=> Add missing const qualifier

include/fmt/core.h
=> Workaround for Intel compiler

include/fmt/format-inl.h
Address https://github.com/fmtlib/fmt/issues/2763
=> Address Issue #2763

include/fmt/format.h
=> Clz builtin may be not constexpr

doc/api.rst
I accidentally closed the PR #2804 while trying to clean the commit tree - now everything should be ok
=> Add `styled` in documentation

ChangeLog.rst
=> Fixed typo in changelog example

CMakeLists.txt
=> Remove -Wl,--as-needed linker option

include/fmt/core.h, include/fmt/format.h, test/format-impl-test.cc
Info:
https://github.com/skeeto/branchless-utf8/issues/8
=> Fix bugs in utf8 decoder

include/fmt/chrono.h, test/chrono-test.cc
Fix for https://github.com/fmtlib/fmt/pull/3115#issuecomment-1279995823
=> Fix overflow error

README.rst
MariaDB 10.7+ has an SFORMAT() function that is a bridge to fmt. It's documented here:
https://mariadb.com/kb/en/sformat/
=> Mention MariaDB amongst the projects that use fmt

include/fmt/ranges.h, test/ranges-test.cc
=> Fixing formatting of range of range of char.

.github/workflows/macos.yml, .github/workflows/windows.yml
=> Improve CI

include/fmt/format.h
Discussion:
https://github.com/fmtlib/fmt/pull/3179#discussion_r1031651469
=> Rename leading_v -> leading_xdigit

include/fmt/format.h, test/format-impl-test.cc
Fix for issue #3213
cc @Epixu @vitaut
=> Add countl_zero function

include/fmt/core.h, test/format-test.cc
=> Fix for issue #3241

include/fmt/ranges.h
=> Remove empty semicolon

src/os.cc
Fix #3292. 
@ChihHao-Su I don't have OpenBSD right now. If you are available, could you check if it's working for you?
=> Fix OpenBSD build error

.github/workflows/doc.yml, .github/workflows/linux.yml
Github Actions caching proxy is at times unreliable
Fixes: #3299
More info: https://github.com/actions/runner-images/issues/7048
=> Add ubuntu mirrors

include/fmt/chrono.h
=> Fix for issue #3325

.github/workflows/cifuzz.yml
Closes #3317 
Changes
- set cifuzz.yml permissions to contents read. Test run with success https://github.com/joycebrum/fmt/actions/runs/4266256497
=> chore: set permission to cifuzz.yml

include/fmt/core.h
This PR fixes https://github.com/fmtlib/fmt/issues/3351
=> Fix CUDA nvcc warning

CMakeLists.txt, src/os.cc
It least Hello World works fine
DJGPP was used as a toolchain
=> fix compilation for MS-DOS

include/fmt/ranges.h
=> ranges: Fix extra semi

README.rst
I haven't done anything in years, and I'm feeling a bit bad that I'm constantly ignoring all issues and PRs here... :D
=> Remove myself from maintainer list

ChangeLog.rst, support/build.gradle
=> Fix spelling

test/format-test.cc
=> Make hex float test more stable

include/fmt/format.h
=> Always assert in FMT_THROW

src/os.cc
Add VxWorks7 user space and kernel space support.
All test cases are passed in Ubuntu Linux 22.04.
=> Add VxWorks7 user space and kernel space support

include/fmt/format.h
=> Fix for issue #3492

README.rst
Just adding the security policy as a part of the README as mentioned in https://github.com/fmtlib/fmt/pull/3356
=> Add security policy to readme

test/format-test.cc
=> Make hex float test more stable on different libc

test/scan.h
Fix spelling: othewise ==> otherwise
=> Fix spelling: othewise ==> otherwise

include/fmt/xchar.h
=> Fix make_format_args ambiguous call

.github/workflows/linux.yml
Reintroduce GCC-11 C++20 into CI
=> Reintroduce GCC-11 C++20 into CI

CMakeLists.txt
=> Fix build with `FMT_MODULE=OFF`

.github/workflows/doc.yml
Error:
```
fatal: could not read Username for 'https://github.com': No such device or address
Error: Process completed with exit code 128.
```
Job: https://github.com/phprus/fmt/actions/runs/9486041580/job/26139437303
=> Fix build docs on forks

include/fmt/ranges.h
=> Remove dependency on <ranges>

include/fmt/std.h
Discussion:
https://github.com/fmtlib/fmt/pull/3834#discussion_r1661121584
=> Remove double has_value check

.github/workflows/lint.yml
=> Simplify lint

include/fmt/std.h
=> Allow disabling <filesystem> by define FMT_CPP_LIB_FILESYSTEM=0

include/fmt/format-inl.h
This resolves the C4702 warnings from issue
- #4280
=> Resolve C4702 unreachable code warnings (fixes #4280)

include/fmt/base.h
=> fix gcc 8.3 compile errors
