test/CMakeLists.txt

On my system (Arch Linux) attempt to compile tests ends up in linkage failure. The proposed patch adds proper library to CMakeLists.txt.

Add format linking to tests

---

format.h

and use it to silence one of the warnings in #96.

Try detecting clang::fallthrough using __has_cpp_attribute

---

.travis.yml
CMakeLists.txt
biicode.conf
biicode/cmake/biicode.cmake
biicode/samples/basic.cpp
biicode/support/travis-build.sh
ignore.bii

It's a full adaptation of cppformat to biicode. Travis has mixed building with and without biicode at same compilation time to keep your library free of bugs in both building systems.
If you want to publish the repo to biicode directly when you make any modification, add to your `biicode.conf` the parent, e.g.:
[parent]
vitaut/cppformat: 0
and execute:
$ bii publish
to publish the block as DEV in [vitaut/cppformat](http://www.biicode.com/vitaut/cppformat)
I just added a folder named **biicode/** with **cmake/** and **samples/** subfolders to make possible this adaptation and .travis.yml can build an executable with biicode

Adapted to biicode via biicode.conf, ignore.bii and CMakeLists.txt

---

CMakeLists.txt
format.cc
format.h
posix.cc
posix.h
test/gtest-extra.cc
test/gtest-extra.h

I decide to split my old [PR](https://github.com/cppformat/cppformat/pull/108) into smaller ones as project owner's request.
I'll create another one after this gets merged.

Use throw() when noexcept is not supported

---

CMakeLists.txt
format.h

Note ```(FMT_GCC_VERSION >= 404 && __cplusplus >= 201103L)``` means ```(FMT_GCC_VERSION >= 407 && __cplusplus >= 201103L)``` actually because of the gcc [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=1773). CMake checks are suggested.
I'll create another PR after this gets merged. As for nullptr, I think it's acceptable as a [monkey patch](http://en.wikipedia.org/wiki/Monkey_patch). Such things have been done by [libc++](http://llvm.org/viewvc/llvm-project/libcxx/trunk/include/cstddef?view=markup#l87).

Use explicitly deleted functions to make types non-copyable

---

CMakeLists.txt
format.h
posix.h

In addition, we use [__GXX_EXPERIMENTAL_CXX0X__](http://stackoverflow.com/questions/2958398/gnu-c-how-to-check-when-std-c0x-is-in-effect#answer-2958415) for better C++11 detection now

Detect static assertion support

---

Android.mk

Android.mk

---

format.cc
posix.cc
test/util-test.cc

Silences more warnings when building on Windows
* Rename  error_code to err_code as @vitaut's suggestion

Silence warnings on Windows

---

format.h

Try to fix https://github.com/cppformat/cppformat/issues/115
Not tested yet due to lacking of MSVC compiler

Use MSVC intrinsics for better performance

---

format.h

Implementation used: http://llvm.org/viewvc/llvm-project/libcxx/trunk/include/support/win32/support.h?view=markup#l135
Note: __builtin_ctzll which targets -m32 does similar thing already
__NOT__ tested due to lacking of MSVC compiler

Emulate _BitScanForward64 on WIN32

---

format.cc

Functions which unconditionally throw exceptions should never return, with or without exception enabled
Tested compiler: AppleClang 6.1, brew g++-4.9 on OS X 10.10.2

Improve behaviors when disabling exceptions

---

format.cc

* thanks @VolodymyrLavrenchuk for pointing this out.
Fixes a [build error on SunOS 5.11](http://pastebin.com/JkxfgLZD) caused through a duplicated variable name (probably in system headers).

Fix build under g++-4.9, SunOS 5.11 i386 i86pc Solaris

---

format.h
test/util-test.cc

Compact arglist

---

doc/build.py

``CalledProcessError`` should only be raised, if ``'No command ...'`` is in ``stderr``, not otherwise.

Fixing doc building with newer pip versions

---

format.h

Child attribute was being instantiated before parent attribute, gives warnings under GCC 4.9.1

Fix warnings

---

CMakeLists.txt

The install target is interfering with CPack when using cppformat as a dependency in another CMake project. When creating a package for said project, CPack also packages all cppformat library files and includes (which is not what we want since cppformat is already statically linked into our project).

new CMake option to disable generating the install target

---

CMakeLists.txt

This will allow to skip tests in case we don't need them (no tests -> faster compiling).

add CMake option to toggle tests (on by default)

---

CMakeLists.txt

Yet another PR, this time with the ability to toggle creation of doxygen documentation (on by default).
By the way, keep up the good work! :+1:

add CMake option to toggle doxygen documentation

---

format.h
test/format-test.cc

This is a bit of fun with C++11 user-defined literals. This brings C++ Format a little closer to Python's `str.format` for literals:
```Python
"{0}{1}{0}".format("abra", "cad")
```
```C++
// C++11 with user-defined literals
"{0}{1}{0}"_format("abra", "cad");
```
The literal `_format` just passes the arguments to `fmt::format` and is equivalent to `fmt::format("{0}{1}{0}", "abra", "cad");`
Literals can be used with named arguments as well:
```Python
"Hello, {name}! Your number is {number}".format(name="World", number=1);
```
```C++
// C++11 with user-defined literals
"Hello, {name}! Your number is {number}"_format("name"_a="World", "number"_a=1);
```
The `_a` literal just constructs a `fmt::arg` under the hood.
Compiler support for UDLs is required. Minimum Clang 3.1, GCC 4.7 or VS2015.
To …

User-defined literals for format and named arguments

---

doc/index.rst

I noticed that named arguments were not covered on the "Overview" page so I added that before the literals. There's also a little bit extra about variadic templates in the "Portability" section.
The new text which describes the UDL functionality is all on the "Overview" page. I'm not really sure what, if anything, should be added to the "API" page. The actual signature of the literal operators
```c++
ImplDetail operator"" _udl(const char *s, std::size_t)
```
is not really useful for the end user. The return type is an implementation detail and the parameter list only matters to the compiler. The final syntax is pretty easy to understand
```c++
"format_str"_format(args...)
"arg_name"_a=value
```
but it doesn't correspond to the literal operator signature.
So I see three options here:
1) …

Document user-defined literals

---

doc/api.rst
doc/build.py
doc/index.rst
format.h

Sphinx 1.3.1 can't parse user-defined literals. This updates the doc build script to the (currently) [latest state on the Sphinx master branch](https://github.com/sphinx-doc/sphinx/commit/4d2c17e043d9e8197fa5cd0db34212af3bb17069) which has the fix.
As for the `fmt::literals` API docs, the examples do most of the explaining. They mirror the `fmt::format` and `fmt::args` examples right above them. The description text just points to the equivalent function. I really couldn't think of anything to write in the description that would be clearer than the example.

Update Sphinx with C++11 literals fix and add fmt::literals API docs

---

format.cc
format.h
test/format-test.cc

You can disable references to *stream libraries by defining FMT_NO_STREAM_LIBRARIES before including the headers.
```
#define FMT_NO_STREAM_LIBRARIES
#include <format.h>
```

Issue 205: Make iostream support optional.

---

CMakeLists.txt

I noticed this while trying to run format-benchmark. Building cppformat on OS X with `BUILD_SHARED_LIBS=ON` results in:
```
ld: unknown option: --as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcppformat.1.2.0.dylib] Error 1
make[1]: *** [CMakeFiles/cppformat.dir/all] Error 2
make: *** [all] Error 2
```
This PR fixes it.
As a side note: The shared lib build is also broken with MSVC and it's a bit more elaborate. I don't think this is a big issue since a shared lib is probably not the optimal way to use cppformat. But just FYI.
This commit will resolve the `ignoring unknown flag --as-needed` warning on MSVC, but the build will still fail because it needs `__declspec(dllexport)` and `__declspec(dllimport)` to know which functions …

Fix shared library build on OS X

---

format.h

If ```/Zc:wchar_t-``` compiler parameter is specified, then ```wchar_t``` is defined as
```typedef unsigned short wchar_t;```
Thus, this leads to conflict in template definition in ```format.h```
You can verify it in any Visual Studio project with spdlog with 
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:wchar_t-")
```
reference: https://msdn.microsoft.com/ru-ru/library/dh8che7s.aspx

MS Visual Studio "/Zc:wchar_t-" compiler parameter support added

---

format.h

Use noexcept in MSVC too. Supported since 1900. (https://msdn.microsoft.com/en-us/library/dn956976.aspx)

MSVC 2015 supports noexcept

---

posix.h

I had an unused typedef warning as shown below. Looks like `static_assert` couldn't be found on clang
This PR fixes it.
```
cppformat/posix.cc:162:3: warning: unused typedef 'Assert163'
[-Wunused-local-typedef]
FMT_STATIC_ASSERT(sizeof(fmt::LongLong) >= sizeof(file_stat.st_size),
^
```

Fix static_assert feature detection on clang

---

format.h

Unfortunately, Intel's C++ compiler defines `__clang__` which means that
some of the pragmas in use that Intel C++ doesn't use will cause
warnings to be generated.

Fix warning when using Intel C++ on OS X

---

format.h

Visual studio issues performance warnings when converting implicitly from bool to int

Silence some performance warnings in Visual Studio

---

posix.cc

Error:
expected unqualified-id before '(' token
int fmt::BufferedFile::fileno() const {
This is an issue with Android NDK and mingw32.

Fix fileno causing compile error when #defined

---

format.cc
format.h
test/format-impl-test.cc
test/macro-test.cc
test/util-test.cc

The proposed PR would reduce the compile time of variadic templates like `fmt::print` and `fmt::format`. The improvement on bloat-test is small but measurable (reduced from 35 to 33 seconds on my system), but that doesn't tell the whole story.
In order to get a more detailed measurement I modified bloat-test to generate tests for any number of arguments. The resulting variadic-test can be [found here](https://github.com/dean0x7d/format-benchmark/commit/fd4e429956ce52ae1bfdd752a9fdbcbaa81b1075). When invoked with `make variadic-test ARGS="1 25 10"` it will generate `fmt::print` statements with `1 <= x < 25` arguments and it will compile each with `10` translation units.
The following figures show the results for Clang and GCC, before and after the proposed PR changes. The data is gathered …

Reduce compile time of variadic functions

---

CMakeLists.txt
format.h
test/CMakeLists.txt

When trying to use cppformat in a shared library I have found that it does not compile in Windows (tested with MinGW32-w64). The reason for this is a lack fo __declspec(dllimport) and __declspec(dllexport) declaration. This PR solves this issue: when compiling shared library, one needs to add definition FMT_EXPORTS and skip it when using the library.
I hope this small improvement can help to make this great library even better.

Declarations for shared library in Windows.

---

format.h

As discussed in #243 this PR changes the way the argument array is initialized.
Instead of recursion, the template parameter pack is expanded in the array initializer.

Reduce compile time of variadic functions (2)

---

format.cc
format.h
test/printf-test.cc

For completeness, add an overload for fprintf that writes to a std::ostream.

Add fprintf overload that writes to a std::ostream

---

format.h

Both clang-cl and Clang/C2 #define `_MSC_VER` but also have support for `__builtin_clz` and `__builtin_clzll`, leading to duplicate macro definition warnings. This change suppresses emulation of clz using `_BitScanReverse` if the `__clang__` macro is defined.

Fixed macro redefinition warnings when compiling with clang-cl.

---

format.h

Changed to only define the MSVC implementations for clz and clzll if the builtins are not available to avoid warnings about an unknown #pragma for "intrinsic".

Fixed unknown pragma warnings for _BitScanReverse.

---

format.cc
format.h

The main reason for this is to avoid a dynamic memory allocation in every format() call with Visual Studio if there are no named arguments. Addresses #261.

Changed ArgMap to be backed by a vector instead of a map.

---

.travis.yml
CMakeLists.txt
cppformat/CMakeLists.txt
support/cmake/testCxx11.cmake
support/travis-build.py
test/CMakeLists.txt

Hi!
This PR increases the test coverage by building and testing the library in c++ 98, 03, and 0x mode with Travis. The older standards are only tested in release mode to reduce the number of builds.

Extend CI tests with older c++ standards

---

cppformat/format.cc

Clang with `-Wimplicit-fallthrough` enabled shows a warning here without
the break. See http://clang.llvm.org/docs/AttributeReference.html#fallthrough-clang-fallthrough

Fix switch fall-through warning

---

cppformat/format.h

-> Fixes warnings about disabled exception support in MSVC
```
2>...\cppformat\cppformat\cppformat\posix.h(112): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ...\cppformat\cppformat\cppformat\posix.cc)
2>...\cppformat\cppformat\cppformat\format.cc(143): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
```

Define FMT_NOEXCEPT empty when exceptions are disabled

---

cppformat/format.cc
test/util-test.cc

This is for non-'Desktop' applications that have a more limited collection of functions.
Addresses #280.

Changed format_windows_error to not need LocalFree

---

CMakeLists.txt
cppformat/CMakeLists.txt

This PR makes the install location for generated cmake files configurable. (requested in [this comment](https://github.com/cppformat/cppformat/pull/267#issuecomment-205868104) in #267).
Details and an example can be found in the commit message of `dcbb6b1`.

Minor packaging improvements

---

fmt/format.h
support/cmake/cxx11.cmake
test/CMakeLists.txt
test/compile-test/CMakeLists.txt

Fixes #311.
The `FMT_USE_USER_DEFINED_LITERALS` check is beginning to resemble a dumpster fire, but as per Intel's [C++11 feature notes](https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler) both the system compiler (gcc/msc) and icc itself must support the given feature:
> On Windows: when using Intel C++ compiler with Visual Studio 2010* or 2012*, the C++11 features supported by Visual C++ 2010/2012 are enabled by default. Use "/Qstd=c++11" to turn on the support for all other cases.
> On Linux or Mac OS X: the C++11 features supported by gcc on the path are enabled by default. Use "-std=c++11" to turn on the support for all other cases.
To make sure the UDL detection still works on any compiler I added a new compile test which checks that the feature …

Fix user-defined literal detection for Intel C++ compiler (#311)

---

test/CMakeLists.txt
test/compile-test/CMakeLists.txt

I noticed some compile test bugs while working on #312 (but these bugs aren't actually specific to Intel's compiler).
1. In `expect_compile` and `expect_compile_error` the cache variable was not always unset because `message(FATAL_ERROR)` exits immediately. Even if a test was fixed it would appear broken until the cache was reset manually.
2.  The expected-to-fail `FMT_STATIC_ASSERT` test was failing for the wrong reason: missing macro instead of the actual static assert.
3.  If the main project was configured with a non-default compiler, `find-package-test` failed with linker errors because `ctest --build-and-test` would still use the system default.

Fix a few bugs related to compile tests

---

fmt/format.h

Fixing https://github.com/fmtlib/fmt/issues/327
Better to check if this API really works on Android. 
Also please check if that is an OK use for the StringRef.

Workaround for missing lconv support in android

---

fmt/format.h

Building under a recent clang compiler causes the use of an extern
template for the BasicData struct. However, the only instantiation of
that structure in format.cc is only done if FMT_HEADER_ONLY is not
defined. This causes the build to fail in C++11 or C++14 mode.
Therefore, only declare the BasicData template as extern if
FMT_HEADER_ONLY is not defined.

Fix building with clang in header-only mode

---

fmt/posix.h

I haven't tested this, but it might also apply to other BSDs

Fix compile on FreeBSD

---

doc/usage.rst

Homebrew package name was changed from cppformat to fmt.
https://github.com/Homebrew/homebrew-core/commit/1e1dfe43b8e69709b1223e1d5182135bc47cbae9

Update usage.rst: change Homebrew package name

---

fmt/format.h

Removes a compiler warning about unreachable code.
Sorry about the white spaces...

Remove unreachable code below FMT_THROW

---

fmt/format.h

The pull request fixes the compilation error on Android's NDK.
```
spdlog/fmt/bundled/format.h:3263: error: undefined reference to 'localeconv'
```

Fix compilation on Android.

---

fmt/format.h

in c++11 compilers
Also use it where the compiler warns.

Add FMT_OVERRIDE macro to allow specifying overriding functions

---

fmt/format.h

I removed CustomValue.size overhead in my PR and keep only types() accessors in ArgList

Extend ArgLists to support serialization/deserialization in third-party components

---

doc/api.rst

This is my attempt to provide documentation for how to use format_arg so one may use a user-defined type in a call to format. This documents the discussion around issue #392. Thanks for your help. I hope you find this contribution useful.

Document use of format_arg for user-defined type

---

fmt/format.cc
fmt/ostream.cc
fmt/ostream.h
fmt/posix.cc
fmt/posix.h
fmt/printf.h
fmt/string.h
fmt/time.h

I suggest removing "fmt/" prefix in *.h, *.cc files inside fmt directory. Consider someone using fmt library as a git submodule or third-party library and has format.h helper file with direct referencing: 
#include "../../modules/fmt/fmt/format.h"
#include "../../modules/fmt/fmt/ostream.h"
Nevertheless I put explicit relative path to format.h and ostream.h I need to add include_directories("modules/fmt") anywhere I use my format.h helper, because ostream.h contins the following inside:
#include "fmt/format.h"
and I believe it could be easily replaced without any side effects with  
#include "format.h"

Remove unnecessary "fmt/" prefix inside fmt directory

---

fmt/posix.cc
fmt/posix.h

In some places `throw` was used instead of `FMT_THROW` which caused the compilation to fail when exceptions are disabled.
I didn't change this in the tests but only in the library itself which might be used by projects that are compiled without exceptions.

Fix Linux compilation with -fno-exceptions

---

fmt/format.cc
fmt/format.h
fmt/posix.cc
fmt/posix.h
fmt/printf.h
fmt/string.h
fmt/time.h
test/format-test.cc
test/mock-allocator.h
test/util-test.cc

Based on [issue 408](https://github.com/fmtlib/fmt/issues/408)
I've added FMT_NULLPTR macro (similar to other emulated language features there) that would expand to NULL or nullptr if available, as gcc isn't happy even with NULL in some cases.
Also added a couple of FMT_OVERRIDE where necessary.

Using FMT_NULLPTR instead of literal 0

---

fmt/CMakeLists.txt
fmt/format.cc
fmt/printf.cc
fmt/printf.h
test/CMakeLists.txt
test/add-subdirectory-test/main.cc
test/find-package-test/main.cc
test/format-impl-test.cc

Issue #418 - Minimal supported library subset

---

fmt/format.h
fmt/string.h

Modified the constructors of `BasicStringRef` and `BasicCStringRef` to accept `std::basic_string`s with any allocator. Also modified and `BasicWriter.str()` to accept custom allocator parameter. This allows the following code to work:
```c++
using scalable_string = std::basic_string<char, std::char_traits<char>, scalable_allocator<char> >;
fmt::MemoryWriter writer;
writer << "Hello from " << scalable_string{"fmtlib"} << '\n';
const scalable_string result_str = writer.str<scalable_allocator<char> >();
```
Modified `StringBuffer` and `BasicStringWriter` to accept custom allocator template parameters for the internal string and the `move_to` parameter.

Add std::basic_string allocator support to StringRef, StringBuffer and relatives

---

fmt/CMakeLists.txt

Currently the `fmt` CMake target exports `-std=c++11` as part of its interface; Meaning any project that links to `fmt` has the `-std=c++11` added to its compilation. However this will override the `-std=<ver>` flag provided by that project. This breaks projects that use C++14 or C++1z. In general I think it's bad style for projects to force a specific dialect, or any compile flags, upon its users. 
This patch fixes the issue by making `-std=c++11` a private flag of `fmt`. This prevent it from infecting downstream users.

Don't export the -std=c++11 flag from the fmt target

---

doc/api.rst
doc/build.py
fmt/CMakeLists.txt
fmt/container.h
test/CMakeLists.txt
test/container-test.cc

A buffer-writer utility pair that allows to append formatted string to an external "standard-compliant" container such as `std::vector` or `std::basic_string`.
*Container* type requirements:
* `typedef CharT value_type;`
* `std::size_t size() const`
* `std::size_t resize() const`
* `CharT& operator[](std::size_t index)`
* contiguous buffer
Cons:
* Adds an extra header file
Pros:
* Directly writes into the external container, passed by ref
* Implicit use of container's allocator
* "Append" feature available for free
* More generic than the buffer-writer pair implemented in `fmt/string.h`
* No modification applied to fmt itself

BasicContainerWriter utility added

---

fmt/printf.h
test/printf-test.cc

Signed integers are formatted as %d
Unsigned integers are formatted as %u
Doubles are formatted as %f
Chars are formatted as %c
Void Pointers are formatted as %p

Allow %s as generic format specifier in printf

---

fmt/format.h

Managed C++ code doesn't have the _BitScanReverse* intrinsics, we must use the fallback code for count_digits etc.

Fix missing intrinsic when included from C++/CLI

---

fmt/format.h
fmt/ostream.h
test/ostream-test.cc

allow to stream user defined types in a MemoryWriter

---

fmt/format.h

When using the NDK 13b toolchain standalone or with CMake, ANDROID is not defined,
but __ANDROID__ is defined instead.
I can't say for sure that is and will always be the case, but it works for me, and I have some unofficial sources: http://stackoverflow.com/a/15335544 and http://markmail.org/message/5ekhfztchs45lz3n#query:+page:1+mid:jfqgzrmwm37uyrt6+state:results

Fix Android not being detected with latest NDK toolchain

---

fmt/format.h
test/format-test.cc

string. Each value is formated according the format specifier.

Add join argument allowing formating list of values separated by a

---

fmt/format.cc
fmt/format.h

To dll export from within a larger dll. See #460 for details.
Note that couple `internal::CharTraits` had to be exported because it is used from within a function defined in the header (that wasn't exported).

Additional FMT_API declarations where needed

---

fmt/ostream.h

Add `override` specifier to `FormatBuf::overflow` virtual function.

Added missing FMT_OVERRIDE specifier to FormatBuf::overflow

---

fmt/format.h

This PR fixes 
```fmt/format.h:2387:3: error: definition of implicit copy constructor for 'SystemError' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated]   ~SystemError() FMT_DTOR_NOEXCEPT;``` 
in clang-3.9

Add default copy constructor to SystemError

---

fmt/format.cc

Take two!
This fixes compiling fmtlib in header-only mode when user code also has
something called 'Arg' defined. Now qualifying Arg struct with internal
namespace.

Don't bring Arg struct into global namespace

---

doc/basic-bootstrap/layout.html

With Sphinx 1.5, this is needed by searchtools.js to display the source
snippets (see sphinx-doc/sphinx#2454).
With earlier Sphinx versions, this is a no-op because the undefined variable
will evaluate to an empty string.

add SOURCELINK_SUFFIX for compatibility with Sphinx 1.5

---

fmt/format.h

i test the the code on https://gcc.godbolt.org/, and only gcc 4.7 works,
gcc 4.6 fail to complie

fmt::internal::is_streamable works on gcc 4.7

---

fmt/format.cc
fmt/posix.cc

This PR reduces the size of what `windows.h` will include by using the define `WIN32_LEAN_AND_MEAN`.
In fact it also help to prevent bad order of inclusion because some header files in Windows need to be include in a good order and that can cause some problems when you use fmt without looking for what it is including.

Don't include the world with WIN32_LEAN_AND_MEAN

---

fmt/format.h
fmt/ostream.h
fmt/posix.h
fmt/printf.h
test/format-impl-test.cc
test/format-test.cc
test/time-test.cc

Removes warnings and errors when compiling in VS 2015 with BUILD_SHARED_LIBS set to "ON".

Allow compiling and using as DLL in windows

---

fmt/format.h

Each instantiation of ArgArray template uses sizeof operator, which returns a std::size_t value. GCC 7.1 warns about invalid conversion (error: conversion to ‘unsigned int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]).

Changing ArgArray template argument from unsigned to size_t

---

doc/usage.rst

Describe cmake use of header-only target

---

fmt/format.cc

Since the 4.0 release is almost there, that function should be removed as described in the comment.

remove unnecessary method

---

fmt/CMakeLists.txt

Another backward compatibility thing removed before 4.0 release.

remove 'FMT_CPPFORMAT' CMake option

---

fmt/format.h

`FMT_USE_USER_DEFINED_LITERALS` macro expands to `defined()` which is undefined behavior.

Fix undefined behavior in UDL macro

---

fmt/format.h

Similar to the Pullrequest #539, `_SECURE_SCL` caused the same  `warning C4574: '_SECURE_SCL' is defined to be '0': did you mean to use '#if _SECURE_SCL'`.  `_SECURE_SCL` is defined in the `MSVC/14.10.25017/include/yvals.h` by Microsoft itself

Update format.h to remove C4574 error on MSVC 14.2

---

fmt/format.h

Adding `[[noreturn]]` to `report_unknown_type` suppresses the Clang/GCC `-Wmissing-noreturn` warning:
Clang outputs:
.../fmt/fmt/format.cc:294:74: warning:
function 'report_unknown_type' could be declared with
attribute 'noreturn' [-Wmissing-noreturn]
...code, const char *type) {
^
GCC outputs:
.../fmt/fmt/format.cc:294:74: warning: function might be candidate for
attribute 'noreturn' [-Wsuggest-attribute=noreturn]
...code, const char *type) {
^

Suppress warning about missing noreturn attribute

---

CMakeLists.txt

This will remove one more warning that can't be stopped from a calling CMakeLists. This possibly should be set to new at some point (CMake 3.3 behavior would be different / better), as well as CMP0048.

Add one more CMake warning fix

---

fmt/format.h
fmt/printf.h

This prevents integer conversion warnings so the library can be compiled with GCC and `-Wconversion` enabled (also `-Werror -Wall -Wextra -pedantic`, but I think the offender was `-Wconversion`) as "discussed" in #552.
Note this change makes possible to build fmt with these flags, but **the unit tests cannot be compiled, googletest triggers a lot of conversion warnings**.

Explicitly cast int -> char to prevent conversion warnings

---

doc/api.rst
fmt/string.h
test/string-test.cc

As per [this](https://github.com/fmtlib/fmt/issues/326#issuecomment-325187523) discussion.

to_wstring added

---

fmt/format.cc
fmt/format.h

Make ArgMap::init not explicitly instantiated

---

fmt/format.cc

This suppresses the Clang warning `-Wzero-as-null-pointer-constant` by using `FMT_NULL` instead of `0`:
```
fmt/format.cc:124:24: error: zero as null pointer
constant [-Werror,-Wzero-as-null-pointer-constant]
FMT_ASSERT(buffer != 0 && buffer_size != 0, "invalid buffer");
^
nullptr
```

Suppress Clang's warning on zero as a null pointer

---

fmt/format.h
test/format-test.cc

Enable `std::string_view` to work with format when compiling with C++17.
Change log:
+ `fmt::StringRef` is constructible from `std::string_view`.
+ `fmt::StringRef` is convertible to `std::string_view` (only explicitly)[1].
+ `fmt::format` accepts `std::string_view` as an argument for the argument list.
[1] This is open to debate. Should it be an implicit conversion, or should it not exist at all? The argument in favor of it is that `std::string_view` is now the common string reference, and all other string implementations could take advantage of it by providing a conversion to it. A counter-argument would be that fmtlib prefers `fmt::StringRef` as the common string reference.

Make format work with C++17 std::string_view

---

fmt/format.h

Microsoft allows customizing the standard version the compiler will target, so a simple _MSC_VER check is inadequate, but __has_include support was added after string_view, so _MSC_VER is still needed.
Also, adding "override" to destructors that are virtual by inheritance.

Added MSVC checking for support for string_view.

---

fmt/format.h
test/mock-allocator.h

This is to avoid using functionality deprecated in C++17. Addresses #579.

Use allocator_traits if available.

---

fmt/format.h
test/format-test.cc

Implementation of FMT_VARIDIC_CONST as discussed here https://github.com/fmtlib/fmt/issues/589

FMT_VARIADIC_CONST - Support for const variadic methods

---

fmt/format.h

Fix for "warning C5030: attribute 'maybe_unused' is not recognized" in VS2015.

Fix for warning C5030 in VS2015

---

fmt/format.h

The warning is produced by template functions in format.h with MSVC 2017 toolchain.

fix warning in header: signed/unsigned comparison

---

fmt/CMakeLists.txt

CMake's GNUInstallDirs knows where particular Linux architectures and
distributions want to have their libraries installed. In particular,
Debian-derived "multi-arch" distributions keep their libraries in triplet
sudirectories under /lib. Other "bi-arch" distributions keep 64-bit
libraries in /lib64.
Including GNUInstallDirs and using CMAKE_INSTALL_LIBDIR and
CMAKE_INSTALL_INCLUDEDIR means that fmt's libraries and header files are
installed in the correct locations.
Tested with OpenEmbedded and on Debian GNU/Linux 9 (the special naming only
applies when installing in /usr.)
I would hope that GNUInstallDirs does something sensible on Windows, but I haven't tested it.

CMakeLists: Use GNUInstallDirs to set install location

---

include/fmt/format.h

It looks like CHAR_WIDTH is a macro in glibc. See [this](https://sourceware.org/ml/libc-alpha/2016-09/msg00225.html).

Avoid conflict with the macro CHAR_WIDTH

---

doc/index.rst

Add a note about the usage of `errno`, as discussed in #614.

Add note about errno to the documentation

---

fmt/format.h
test/CMakeLists.txt
test/format-test.cc

Also, added _POSIX_C_SOURCE to make library compile and pass on all tests on Cygwin environment.

Added support for pre-c++17 experimental string_view

---

fmt/format.h

i'd like to propose the following (ugly) helper: we're using v3 in several projects, but the transition from v3 to v4 was not straight-forward as printf functionality was moved out of format.h into a separate header.
this hack helps us to update to v4 without immediately changing all of our product code, but allows us to incrementally adapt the includes.

v3 v4 transition helper

---

fmt/format.h

Fixes the following warning:
```
warning: will never be executed [-Wunreachable-code]
sizeof(signbit(x)) == sizeof(int))) {
^~~~~~~~~~~~~~~~~~
```

Fix unreachable code warning when signbit returns bool

---

include/fmt/posix.h

OpenBSD lacks `strtod_l`, so the `Locale` class won't compile. Looking around, this problem has apparently occurred in other environments as well (#388, #345), so I fixed it the same way they were fixed: by appending ` && !defined(__OpenBSD__)` to the preprocessor condition gating the definition of the `FMT_LOCALE` macro.

Fix build on OpenBSD

---

doc/syntax.rst

Fixes https://github.com/fmtlib/fmtlib.github.io/issues/2

Add format example for padded hex byte

---

include/fmt/core.h
include/fmt/format.h

Fix warnings under MSVC

---

include/fmt/core.h
include/fmt/format.h

First commit fixes a `-Wpedantic` warning when compiling gcc and clang.
Second commit defines `FMT_UNION` as `union` rather than `struct` on clang.

Fix warnings on gcc and clang

---

include/fmt/core.h
include/fmt/format.h
src/format.cc

When using fmt as a shared library with FMT_SHARED in MSVC, I got linker errors for the library consuming fmt.
Two definitions could not be found:
- `fmt::internal::error_handler::on_error(const char *message)`
- `char fmt::internal::thousands_sep(locale_provider *lp)`
Since those definitions are hidden in `format-inl.h` I added `FMT_API` macros to make the functions part of the DLL interface.

Fix linker errors using fmt as shared library in MSVC

---

include/fmt/format.h

Hi,
first, thanks for the great library. I am currently porting my own software to Windows and it turned out that MSVC/VS2017 is complaining a lot in my code (99% of the build output is `fmt` lib related).
It turned out that I could track it down to the following change of this PR.
There might be surely another way (I didn't dig too deep into the template-voodoo of this project), such as the template-ification of `align_spec`, so that in line 1144 (`wchar_t fill_;`) would be more generic.  But I'd like to get your feedback, and probably an early merge, so that I do not need to manually patch locally.
Best regards,
Christian Parpart.

fixes MSVC compiler warning bloat (Visual Studio 2017, latest updates)

---

CMakeLists.txt

Fmt sets the `FMT_VERSION` variables after project(), so the NEW option here is safe. Currently including Fmt causes newer versions of CMake to throw warnings. (This problem was fixed in Fmt master)

Stop newer CMake's from warning about OLD policy

---

CMakeLists.txt

Setting the `OLD` version of [this policy](https://cmake.org/cmake/help/latest/policy/CMP0063.html) (or even if it is unset and CMake minimum_version is set below 3.3, which it is) does the wrong thing; it causes GCC to spew a mass of warnings if you try to use fmt from a project that has set hidden symbols. Setting this to `NEW` fixes the issue.
Patch to 4.x because both policy statements are missing from master.

Fix warnings when with master project set to hidden

---

include/fmt/format.h
test/format-test.cc

This fixes cases where arg_formatters are reused, like with arg_join.

Fixed arg_formatter_base::write_pointer to not mutate the format specs.

---

include/fmt/core.h

Remove checking the value of a potentially undefined macro `_LIBCPP_VERSION` and replace it with `defined(_LIBCPP_VERSION)`. Previously, this caused warnings on both gcc and clang if `-Wundef` was enabled.

Fix usage of potentially undefined macro `_LIBCPP_VERSION`

---

test/posix-mock-test.cc
test/posix-mock.h

The fix for #433 is correct for FreeBSD versions less than 12.
FreeBSD 12 changed the type of freelocale to the type defined by POSIX. Check the FreeBSD version when building for FreeBSD.

Fix #433 for FreeBSD 12

---

fmt/format.h

Else on windows across DLLs the vtable is not visible which causes linking error

Mark the whole class FormatError as FMT_API

---

CMakeLists.txt

Otherwise `ranges.h` will not be installed.

Add ranges.h to FMT_HEADERS in CMakeLists.txt

---

include/fmt/core.h
include/fmt/format.h

MSVC is timid about evaluating constexpr functions unless it has to, so the "TYPES" variables end up in read-write memory even though the optimizer removes the initializer. Making TYPES constexpr causes MSVC to try harder to initialize these variables at compile time, which also ends up completely removing the (named) variable from the final compiled binary.
Fixed a data truncation warning being reported in ostream-test.

MSVC improvements and data truncation cleanup.

---

include/fmt/ranges.h
test/ranges-test.cc

std::string and types like it are now printed in double quotes "str".
chars are now printed in single quotes 'A'.
```cpp
#include <tuple>
#include <vector>
#include <string_view>
#define FMT_HEADER_ONLY
#include <fmt/ranges.h>
int main() {
std::tuple tup = {1, '1', "10", std::string("20"), std::string_view{"30"}};
fmt::print("{}\n", tup); // (1, '1', "10", "20", "30")
std::vector vec = {'1', '2'};
fmt::print("{}\n", vec); // {'1', '2'}
std::vector vec2 = {"2", "3"};
fmt::print("{}\n", vec2); // {"2", "3"}
}
```

quotes for string support.

---

include/fmt/core.h
include/fmt/format.h

Just a couple static casts to fix -Wsign-conversion warnings.
There are a couple of weird things though, please take a look.
For example, why is precision an `int` and not an `unsigned`?

Fix sign conversion warnings

---

include/fmt/format.h

Fixes the other half of #802.
The return is unreachable since all paths either return or break, which gets them out past the return.
PS: This bug is a showstopper for me for upgrading to fmt 5.1.0, since I get a massive number of copies of warnings in the build process.

Fixing return unreachable warning on NVCC

---

CMakeLists.txt

Slightly uglier than #803 , but should support MSVC's built-in CMake.

Reduce warnings, support #809

---

include/fmt/core.h
test/format-test.cc

This allows construction of basic_format_args from a dynamic set of arguments. The syntax is a little clunky and could probably be improved but this at least enables the functionality.

Add support for dynamic arg sets

---

include/fmt/format.h

Since the commit 691a7a9 compile-time string checking is (accidently?) not possible anymore.
With this change, it should be possible again.

Re-enable compile-time format-string checking

---

include/fmt/format.h

Hello. 
The situation is similar to #146. 
Got a lot of C4127 warnings (constant expression) on /W4 in VS 2017. This fixes it via the same approach that was previously used.

Fix C4127 warning in basic_writer<Range>::write_double

---

include/fmt/format-inl.h

When compiling with g++8, I get the following two errors:
```
include/fmt/format-inl.h:400:29: error: conversion from ‘int’ to ‘char’ may change value [-Werror=conversion]
buffer[size++] = zero + static_cast<char>(digit);
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
include/fmt/format-inl.h:416:28: error: conversion from ‘int’ to ‘char’ may change value [-Werror=conversion]
buffer[size++] = '0' + digit;
~~~~^~~~~~~
```
With this change, the errors are gone.

Remove conversion compiler warnings

---

include/fmt/format-inl.h

This change enables FMT_FALLLTHROUGH also for GCC-Compilers in the versions 7 and 8.

Get rid of implicit-fallthrough warn. in GCC 7 and 8

---

include/fmt/format-inl.h

Get rid of the following warning:
conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]

Get rid of conversion warning in gcc-4.8

---

doc/api.rst

Using unscoped enum formats to ints

[Docs] Changed to use scoped enum

---

include/fmt/core.h

This replaces the confusing "use of incomplete type" when formatting an unknown type with a nice static_assert, like this:
```
In file included from /home/foonathan/Programming/fmt/include/fmt/format.h:54,
from /home/foonathan/Programming/fmt/test/add-subdirectory-test/main.cc:1:
/home/foonathan/Programming/fmt/include/fmt/core.h: In instantiation of ‘struct fmt::v5::formatter<ostream_only, char, void>’:
/home/foonathan/Programming/fmt/include/fmt/core.h:590:56:   required from ‘static void fmt::v5::internal::value<Context>::format_custom_arg(const void*, Context&) [with T = ostream_only; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>]’
/home/foonathan/Programming/fmt/include/fmt/core.h:576:19:   required from …
```

Improve error message when formatting unknown types

---

include/fmt/format.h

The issue #742 seems to also affect other compilers using the EDG C++ Front End, such as the NVIDIA CUDA compiler.
`nvcc` from CUDA 9.2 gives the following error for me when including fmt 5.2.0 in a CUDA source file built with `-std=c++14`:
/usr/include/fmt/format.h(3677): error: a literal operator template must have a template parameter list equivalent to "<char ...>"
This patch fixes the issue by also disabling `FMT_UDL_TEMPLATE` when built under nvcc.

Fix building under NVIDIA's CUDA compiler

---

include/fmt/color.h
include/fmt/format-inl.h
include/fmt/format.h

Provide more overloads for the wide string flavour

---

include/fmt/color.h
include/fmt/core.h
include/fmt/format.h

constrain templated format_to on proper format string type.

---

include/fmt/core.h
include/fmt/format.h
test/format-test.cc

Parameterize core functions on the type of the format string.

---

include/fmt/core.h

The non-`char` contexts were probably never excercised in this regard.

Fix non-matching char types.

---

include/fmt/printf.h

Parameterize printf functions on the type of the format string.

---

doc/index.rst

In the Format API section, it says fmt:print writes to a file, but it
writes to a stream as referenced from fopen(3), "stream open
functions". Also in the Safety section a typo; tim should be time.

minor documentation corrections

---

include/fmt/format-inl.h
include/fmt/format.h
src/format.cc
test/format-test.cc

Issue #873 indicates that this class is no longer required,
as it has been superseded by a new API.
Fixes #873

Remove basic_fixed_buffer.

---

doc/CMakeLists.txt
doc/build.py

this allows us to use sphinx-build-3, as user might already in a python3
world, and distros, like fedora 28, tend to add a "-3" suffix to sphinx-build.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

find sphinx-build before calling build.py

---

.gitignore
CMakeLists.txt
support/cmake/fmt.pc.in

This makes `fmt` easier to use from `meson` or other tools that use `pkgconfig`.

add fmt.pc for pkgconfig

---

include/fmt/format.h
test/format-test.cc

std::back_insert_iterators model the OutputIterator concept but differ considerably in their traits and behavior. In particular the former made compilation to fail when format_to_n is given a back_inserter as first argument. The emulation of an OutputIterator is not perfect due to the behavioural differences of back_insert_iterators (e.g. assignment always implies increment) but good enough to be used within fmt's machinery.

fix: 'format_to_n' compiles 'std::back_inserter' arguments

---

test/format-impl-test.cc

checks for clashes with other function overloads in fmt with templated parameters on the first or second position in the parameter list

additional test for print with background color

---

include/fmt/core.h
include/fmt/format.h
test/format-test.cc

Add support to compile time non-char format

---

include/fmt/format.h
test/format-test.cc

constrain the `OutputIt` function parameters to be models of `mutable iterators`.

check for property 'mutable iterator'

---

.travis.yml
support/AndroidManifest.xml
support/build.gradle

I'm glad to make another PR for this library. Appreciate for your maintenance works.   
More changes can be required when Gradle 5.0 is released. Please mention me if the build fails. 
Updated Gradle and Travis YAML for Android build. [Build Log](https://travis-ci.org/fmtlib/fmt/builds/449942981) 
> Seems like the build log is crazy. :(
- Applied latest Gradle (ver. 4.10.2) and plugin (ver 3.1.3)
- Latest NDK and `c++17` for cxx flag
For more detailed explanation, please reference this commit: https://github.com/fmtlib/fmt/pull/926/commits/65134fe3390d732895aa98201e5b850a7686e087
- #649

Update of Android build (with Gradle)

---

include/fmt/format.h

This closes https://github.com/fmtlib/fmt/issues/932.

Fix incompatibilities with c++2a mode in clang

---

include/fmt/printf.h
test/printf-test.cc

Add utitlity functions to allow the easy creation of `fmt::printf_args` and `fmt::wprintf_args`.

add make_printf_args and make_wprintf_args functions

---

include/fmt/time.h

The sheer presence of 'std::gmtime' or 'std::localtime' gives rise to C4996 warnings in Microsofts compilers. Alas, the 'fallback(internal::null<>)'functions containing these library calls are never ADL-picked in the respective 'handle(internal::null<>)' selectors. Therefore hiding the fallbacks from msvc is perfectly fine.

Eliminate msvc compiler warnings (#931)

---

support/cmake/fmt.pc.in

CMAKE_INSTALL_INCLUDEDIR used in the fmt.pc.in is converted to just "include", not a full path, on OSX. (not tested on other envrionments).
Thus `pkg-config fmt --cflags` results `-Iinclude`.
The same applies to CMAKE_INSTALL_LIBDIR. 
I suppose that they should be CMAKE_INSTALL_FULL_x variables.
Releated information:
* https://gitlab.freedesktop.org/poppler/poppler/commit/c45efa2d7e0db8a4ace0e8c6955b3fa48dc6d070
* https://bugzilla.redhat.com/show_bug.cgi?id=795542

Use full paths for fmt.pc.in

---

include/fmt/core.h

This squashes nasty narrowing conversion warnings.

Make return type of basic_format_args::max_size() consistent.

---

include/fmt/core.h

Currently core.h overrides my -DFMT_EXCEPTIONS=0 flag supplied from my CMake project which includes fmtlib as a third-party dependency.
This minor edit allows a parent CMake file to disable exceptions by explicitly setting the FMT_EXCEPTIONS flag to 0.

Do not override user provided compile flag

---

include/fmt/format.h

vs2017 complier error log:
spdlog\fmt\bundled\format.h(3036): error C2666: “operator +”:
....
...
spdlog\fmt\bundled\format.h(3036): note: or “builtin C++ operator+(char [22], __int64)”
spdlog\fmt\bundled\format.h(3036): note: try to match the parameter list“(char [22], fmt::v5::format_int::<unnamed-enum-BUFFER_SIZE>)”
format.h 3036 line:
char *ptr = buffer_ + BUFFER_SIZE - 1;//The 'BUFFER_SIZE' exist implicit conversion

Fix ambiguous complier error C2666 in vs2017.The '+' opeator may cause ambiguity.

---

include/fmt/color.h
test/format-impl-test.cc

This patch adds support for text emphasis: bold and underline.
```c++
#define FMT_HEADER_ONLY
#include "include/fmt/color.h"
#include "include/fmt/format.h"
int main() {
fmt::print(fmt::emphasis::bold, "bold\n");
fmt::print(fmt::emphasis::underline, "underline\n");
fmt::print(fmt::emphasis::bold, fmt::color::red, "bold and red\n");
fmt::print(fmt::emphasis::underline, fmt::color::red, fmt::color::yellow,
"underline, red and yellow\n");
}
```

Add experimental emphasis support

---

doc/usage.rst

after executing `cmake <path-to-fmt>, the output .sln file is FMT.sln not FORMAT.sln.

DOCS: VS .sln filename changed from FORMAT.sln to FMT.sln

---

test/gtest-extra-test.cc
test/posix-mock-test.cc
test/posix-test.cc

scoped_ptr was removed in with gtest google/googletest@e857f9cdd998136b9aad634272301f5b2d0476ea.

Replaced usage of gtest's internal scoped_ptr with unique_ptr.

---

include/fmt/prepare.h
test/prepare-test.cc

These problems are pointed out by clang-tidy and fail compilation on msvc at /W4 /WX.

Fix compile errors due to name-hiding and an unused function argument.

---

include/fmt/chrono.h
include/fmt/format.h
test/chrono-test.cc

The formatting syntax follows p1361r0, augmented by a precision field as proposed in #1004.

Implement precision for floating-point durations.

---

include/fmt/chrono.h
test/chrono-test.cc

Howard Hinnant's 'date' library recently gained these two new formatting specifiers. This implementation in {fmt} includes support for 'std::chrono::duration' specializations with floating-point representation types and user-definable precision.

Implement 'chrono' formatting specifiers '%Q' and '%q' (#1004)

---

include/fmt/color.h
include/fmt/core.h
include/fmt/format.h
include/fmt/prepare.h
test/core-test.cc
test/format-impl-test.cc
test/format-test.cc
test/ostream-test.cc

This PR marks features commented as deprecated with attributes; `[[deprecated]]` if compiled with C++14 and `__attribute__((deprecated))` or `__declspec(deprecated)` if not.
I was able to replace most of the cases where deprecated functionality was used in the library, but one case lingers: https://github.com/eliaskosunen/fmt/blob/599632ee226d74d6c34d89290ebabd7320c90afe/include/fmt/format.h#L3061
`arg_map::init` takes `const basic_format_args<Context>&` as its sole argument, which can only be extracted from `context_base` with the deprecated member function `args()`.

Mark deprecated functionality with attributes and remove usage of such features

---

include/fmt/ostream.h
include/fmt/prepare.h
include/fmt/ranges.h
test/ostream-test.cc

It seems that the doc doesn't explicitly ban overloading comma operators. So this PR adds guards against overloaded comma operators by sprinkling void casts.
Here is a (nonsense) test case:
```
#include <iostream>
#include "fmt/format.h"
#include "fmt/ostream.h"
template <typename OStream>
struct ostream_with_comma_op
{
std::ostream& os;
ostream_with_comma_op(std::ostream& _os) : os(_os) {}
template <typename T>
ostream_with_comma_op& operator<<(T const& t)
{
os << t;
return *this;
}
};
template <typename OStream, typename T>
void operator,(ostream_with_comma_op<OStream> const&, T&&);
struct ouch {};
ostream_with_comma_op<std::ostream> operator<<(std::ostream& os, ouch)
{
os << "ouch";
return ostream_with_comma_op<std::ostream>(os);
}
int main ()
{
std::cout << fmt::format("{}", ouch{}) …
```

(Unwillingly) protect against overloaded comma operators in decltype

---

test/prepare-test.cc

Since C++17, using template specialization `std::allocator<void>` in any shape or form (even just mentioning it) is deprecated! A simple workaround is replacing `void` by another (preferably empty) type, e.g. `fmt::monostate`.
Found by Clang 9 in Visual Studio.

Fix library deprecation warning

---

.travis.yml
support/build.gradle

Updated Android NDK build with Gradle.  
[Build Log](https://travis-ci.org/luncliff/fmt/jobs/491193775) 
* Changed install method of Gradle
* from: `wget` + `unzip`
* to: [sdkman](https://sdkman.io/)
* Android Gradle Plugin version
* [`3.1.3` >> `3.3.0`](https://github.com/fmtlib/fmt/pull/1039/commits/c60e452f354c7f6f7bfa0ab7620da03535e70fc5#diff-033fc341eae12ca4178f216c37b66148R17) 
* Name for the build matrix item
* [`Android NDK (Gradle)`](https://github.com/fmtlib/fmt/pull/1039/commits/c60e452f354c7f6f7bfa0ab7620da03535e70fc5#diff-354f30a63fb0907d4ad57269548329e3R86)
Previous builds with 4.10.2 generated [**humongous** log](https://travis-ci.org/fmtlib/fmt/jobs/490982331) for review and debug. I applied later version(5.x) to reduce them. Please reference the build log. However, as far …

Gradle 4.10 >> Gradle 5.2

---

doc/api.rst
include/fmt/core.h

Document that fmt::arg takes a non-owning
reference, even if that reference is to
a temporary. As such, users should make sure
the lifetime of the reference lasts as long
as the named argument.
Disable doxygen for deleted overload.

Clarify lifetimes of named_arg parameters

---

include/fmt/format.h
include/format

Some small changes required for me to compile with stricter compiler flags

Fixes for some pedantic warnings

---

include/fmt/format.h
test/format-test.cc

This is so that the format with a text_tyle will compile even if
header-only mode isn't enabled. Addresses #1063.

Declare the size of RESET_COLOR.

---

CMakeLists.txt

Minor cmake improvement that defaults FMT_PKGCONFIG_DIR properly to a relative path. Currently FMT_PKGCONFIG_DIR will be defaulted to an absolute path based on the initial value of CMAKE_INSTALL_PREFIX, and does not automatically change with it.

cmake: default FMT_PKGCONFIG_DIR to a relative path

---

include/fmt/core.h

Not sure if this is the ideal or correct solution, but this is how I got around issue #1085 

Forward declare is_string<FILE*> specializations

---

include/fmt/format.h
test/format-test.cc

This is so that FMT_STRING can be used in a template.

Added missing typename to FMT_STRING.

---

CMakeLists.txt

Most pkgconfig files contain a Libs: variable, which is either /usr/lib
or /usr/lib64. If a 32bit and a 64bit variant of fmt libraries is
installed, the last one wins. As a result compiling for the other
bitsize will fail.
Instead of sharedir use libdir as install target.
Fixes commit 9d0c9c4bb145a286f725cd38c90331eee7addc7f
Fixes commit 287342dab10a5a96479b3e21cd11ce671ed8125c
Signed-off-by: Olaf Hering <olaf@aepfle.de>

install pkg-config file into libdir

---

include/fmt/format.h

Extend basic_writer with write() method for doubles with optional format_specs argument

---

include/fmt/format-inl.h

handle fwrite results #1098

---

CMakeLists.txt

This pull requests adds the minimal requirements of `fmtlib` to the CMake targets.
This is needed so that the users don't have to do it on all their target linking with `fmt::*`.
A cmake version check is added since the `cxx_std_11` compile feature is not available before CMake 3.8.
Note that without this feature required by the user, such an error can occur:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/type_traits:35:/usr/bin/../lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/bits/c++0x_warning.h:32:2: error: This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support \
I …

Add compile features for cmake 3.8+

---

include/fmt/chrono.h
include/fmt/core.h
include/fmt/format.h
test/format-impl-test.cc
test/gtest-extra-test.cc

Enable [[noreturn]] some.

---

doc/api.rst

Change refs to fmt/time.h -> fmt/chrono.h
RST label rename time-api -> chrono-api

doc: update references to "time" API to be "chrono"

---

include/fmt/printf.h
test/printf-test.cc

I work for the Profidata AG which is using the libfmt version 4.1.0. A former colleague of mine (spacemoose) requested the expandability of the PrintfArgFormatter (now printf_arg_formatter) in the following issue: https://github.com/fmtlib/fmt/issues/335.
I have the task to update the libfmt dependency to 5.3.0 and ensure that we still have this feature available. Since I have a little bit of time pressure to finish this I had to balance the time of learning the code structure and the fixing itself. So I hope my approach in this change is ok.
Brief explanation what I did:
In order to be able to override the behaviour of the printf_arg_formatter I had to decouple the …

Restructure printf_arg_formatter to make it customizable

---

include/fmt/format.h
test/format-test.cc

It is a bit noisy to add `.get()` when formatting unique_ptr and shared_ptr. This patch also convert `std::unique_ptr/std::shared_ptr` to `const void *` in `fmt::ptr`.

fmt::ptr: support unique_ptr and shared_ptr.

---

test/chrono-test.cc

The following assertion was triggered by fuzzing with chrono duration:
```
constexpr typename std::make_unsigned<_Tp>::type fmt::v5::internal::to_unsigned(Int) [with Int = long int; typename std::make_unsigned<_Tp>::type = long unsigned int]: Assertion `(value >= 0) && "negative value"' failed.
```
This pull request adds a unit test that triggers the same assertion.

trigger assertion in to_unsigned

---

include/fmt/ostream.h

The gcc-7.2.0 compiler (and others) were giving shadowed variable warnings for this include file.  A simple renaming of a couple local variables eliminates the warnings.

Eliminate shadowed variable warnings from gcc-7.2

---

include/fmt/time.h

Fixed a compile error under MSVC (#1143).

---

include/fmt/chrono.h
include/fmt/core.h
include/fmt/format-inl.h
include/fmt/format.h

`I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.`
See #1140

Fix compilation error under MSVC 19.21 (#1140)

---

_config.yml
include/format

This seems to fixes errors when include <format> in issue #1158

Fix advance_to() and begin() using iterator

---

.travis.yml

I think it would be nice to have the existing C++17 support being proved by a CI job.

Add C++17 builds to travis

---

include/fmt/format-inl.h
include/fmt/format.h

count_code_points(basic_string_view<char8_t>) was defined in
fmt/format-inl.h, and only declared in fmt/format.h, but not defined
in src/format.cc. This commit moves the overload to fmt/format.h and
inlines it.

inlines count_code_points(basic_string_view<char8_t>)

---

include/fmt/prepare.h
test/prepare-test.cc

It should fix #1169. Added a couple of tests to prevent such issues in the future. Please, let me know if I forgot about any `prepared_format::format_to` use case.

Fixed issue with formatting to an array of chars

---

include/fmt/core.h
include/fmt/format-inl.h
include/fmt/format.h

Fix undefined reference & and one warning

---

.travis.yml
CMakeLists.txt
include/fmt/chrono.h
include/fmt/format-inl.h
include/fmt/format.h
include/fmt/safe-duration-cast.h
support/travis-build.py
test/chrono-test.cc
test/fuzzing/.gitignore
test/fuzzing/CMakeLists.txt
test/fuzzing/README.md
test/fuzzing/build.sh
test/fuzzing/chrono_duration.cpp
test/fuzzing/fuzzer_common.h
test/fuzzing/main.cpp
test/fuzzing/named_arg.cpp
test/fuzzing/one_arg.cpp
test/fuzzing/sprintf.cpp
test/fuzzing/two_args.cpp

Should perhaps the safe duration cast be on by default, not only during fuzzing?

Merge the fuzzers

---

test/format-impl-test.cc

Fix FormatTest.StrError on Solaris

---

include/fmt/core.h
test/format-test.cc

A regression appeared in dd8cc8b for compile-time checking of const references.
Prior to dd8cc8b, all callers of `make_args_checked` had the equivalent of `remove_const_t` and `remove_reference_t` via parameter type deduction. Now only `remove_reference_t` is present which means custom type formatter specializations will not be selected unless they have been explicitly specialized with a const type. I am assuming that this is not the intended behavior and have added `remove_const_t` in addition to `remove_reference_t`.

Remove const qualification in compile-time checks

---

include/fmt/core.h

This adds an opt-in macro `FMT_ENFORCE_COMPILE_STRING` to ensure universal usage of compile strings. Some projects may wish to enable this policy in order to catch issues that would otherwise manifest at runtime.

Opt-in macro to enforce use of compile-time format strings

---

include/fmt/color.h

This allows fmt to be compiled with `-fno-exceptions`.

Use `FMT_THROW` in fmt/color.h.

---

doc/usage.rst

Fix typo in usage.rst

---

include/fmt/format-inl.h

The Windows console host will not correctly present `wchar_t` character streams unless the file mode is set to `_O_WTEXT`. These changes modify the various users of `fwrite_fully` to temporarily set the character mode with the aid of a RAII helper class.

Use fputws for outputting wide strings

---

include/fmt/format.h

This is a few couple improvements to literals formatting API.
- It uses forwarding references in the UDL template version instead of const references.
- Simplifies the overly verbose return type of `udl_formatter`.
- Makes use of `basic_string_view` to store the format string and argument name instead of raw character pointers.
- Makes all the literal operators `constexpr`.
- ~~Adds the possibility of defining `FMT_USING_LITERALS` to allow all code at a project level to use the `_format` and `_a` operator.~~

User-defined literals improvements

---

doc/usage.rst

Fix documentation for importing header only target with CMake

---

include/fmt/core.h
test/format-test.cc

This PR correctly prints values of such enums:
`
enum E{
I = 5000000000ULL
};
`
Test update is needed because "0" may not detect an error.

Map not int enum to correct underlying_type

---

include/fmt/format-inl.h
src/posix.cc

using instead of typedef.
climits instead of limits.h
Added missing cast to size_t.

Fix minor clang-tidy warnings

---

include/fmt/chrono.h
include/fmt/core.h
include/fmt/format-inl.h
include/fmt/format.h
include/fmt/printf.h
test/format-impl-test.cc
test/format-test.cc

This is an initial implementation. I want to hear opinions before trying to extend it to other platforms and adding tests for it.

Add support for built-in int128 when available

---

include/fmt/format.h

It happens only vs2015 - and this fixes it.

Fixed vs 2015 warning about unused variable when grisu is off

---

support/cmake/fmt.pc.in

These variables get set to /usr/lib and /usr/include , which is totally wrong in a cross compilation
environment.
Changed to standard pkgconfig values consistent with most other ones.

fmt.pc.in: Fix for cross compilation

---

include/fmt/compile.h
test/compile-test.cc

Fixes `get` and `struct unknown` name clash in header-only mode (see #1324). Also added a simple test for multiple types in `fmt::compile` since `get` works now.
Also, `get` should probably take universal references of arguments and forward them.

Fix errors in fmt/compile.h

---

include/fmt/safe-duration-cast.h

Bug reported here seven weeks ago:
https://developercommunity.visualstudio.com/content/problem/675854/fmtlibs-safe-duration-cast-doesnt-compile-in-vs201.html
But even calling attention to it by saying "you can't compile a library that's the basis for a C++20 proposal" wasn't enough to get any attention.

workaround VS2019 Update 3 compiler bug.

---

README.rst

One more python reference, this one acknowledging the `str.format` function.
A grep of the codebase for `python.org` shows no remaining Python 2 references.

Repoint one more Python 2 link to Python 3

---

include/fmt/printf.h
test/core-test.cc
test/printf-test.cc

1. The change in include/fmt/core.h fixes "shift exponent -4 is negative" in
PrintfTest.InvalidArgIndex
`do_get` is called with index -1 when `basic_printf_context.arg` is called
with id 4294967295 when basic_printf_context::get_arg subtracts 1 from
arg_index 0 in the format string "%0$d".
2. The change in test/core-test.cc fixes "reference binding to null pointer" in
BufferTest.Ctor
buffer.operator[] attempts to return a reference to `buffer.ptr_[0]` when
`ptr_` in `mock_buffer<int> buffer` is null.
2. The change in test/printf-test.cc fixes "signed integer overflow" in
PrintfTest.Length
This occurs in `TestLength<long long>("ll")`, since its minimum value minus
one does not fit in long long.
This fixes all UBSAN reports except one in format-test (#1344).
I agree that my contributions …

Fix undefined in core-test and printf-test

---

test/format-test.cc

When `MoveCtor` performs `check_move_buffer`, the buffer allocator becomes null, but then `MoveCtor` attempts to use it to allocate a dynamic buffer. This succeeds nevertheless because a typical `std::allocator<char>::allocate` does not use `this`, so it does not crash when `this` is null.
Fixes #1344

Fix undefined in format-test

---

CMakeLists.txt
include/fmt/format.h
test/core-test.cc
test/test-assert.h

Another approach to not trigger `-Wdeprecated` and `-Wweak-vtables` after the discussion in #1334.

 Add defaulted copy and move operations to format_error and system_error 

---

include/fmt/core.h
include/fmt/format-inl.h
include/fmt/format.h
test/core-test.cc
test/locale-test.cc

This fixes #1353 and is the first half of the fix for #1336.
I suggest reviewing commits one by one.

Distinguish float type formatting from double

---

include/fmt/format-inl.h
include/fmt/format.h
test/format-impl-test.cc
test/grisu-test.cc

Support single precision floats in grisu formatting

---

include/fmt/core.h

If you compile using `nvcc` and pass the option `--expt-relaxed-constexpr` it will crash with an internal compiler error. This modification prevents using `constexpr` in `fmtlib` when compiling using `nvcc` and prevents the crash.
To clarify, this seems to be necessary on CUDA 10 with `gcc(5->7)` as the host compiler (every `gcc` version I tested). I did not have the chance to validate if other CUDA versions suffer from this same issue.

Patch compiler error when building using nvcc

---

include/fmt/format-inl.h
include/fmt/format.h
include/fmt/printf.h

…n operation
format.h(2808,1): warning C4127: conditional expression is constant

Fix more Visual Studio 2019 pedantic warnings

---

include/fmt/format.h
test/format-test.cc

This fixes #1389. The new test in format-test.cc fails in the absence of changes to format.h.

Fix UTF-8 truncation

---

include/fmt/format-inl.h
include/fmt/format.h
src/format.cc
test/format-test.cc
test/locale-test.cc
test/std-format-test.cc

PR for [#1393](https://github.com/fmtlib/fmt/issues/1393)

Use grouping() from locale for specifier 'n'

---

include/fmt/core.h
test/core-test.cc
test/format-test.cc

This will allow users to do SFINAE-friendly checks for
the formattability of a type.
Fixes #1369

Move has_formatter into the public fmt namespace.

---

include/fmt/core.h
include/fmt/ostream.h

I'm wondering if the overridden locale can be passed to ostream. Here is a code with the current behavior:
```cpp
struct S
{
string a;
int b;
};
ostream& operator<<(ostream& os, const S& s)
{ return os << "{" << s.a << ": " << s.b << "}"; }
locale::global (locale ("fr-FR"));
format (locale("en-US"), "{} {:n} {}", 1234, 1234, S {"test", 1234});
// gives 1234 1,234 {test: 1 234}
```
For known types (including `chrono`), `format` is using `C` locale or the overridden locale. In this example, I don't see the interest to display the result of ostream with the `global` locale...
I can override the current behavior by implementing the following for each of my own classes:
```cpp
namespace fmt
{
template <>
struct formatter<S> : formatter<basic_string_view<char>, char>
{
using base_type = …
```

Use overridden locale in ostream

---

test/format-test.cc

This fixed a compilation error of the OS X 10.11.6 C++ compiler:
./fmt/test/format-test.cc:1861:16: error: default initialization of an object of const type 'const Answer' without a user-provided default constructor
const Answer const_answer;
^
{}

test: add default constructor for a const value

---

README.rst

Finally a bug crept in, so we could verify that the bug tracker link worked properly :-)

fix bad oss fuzz link in the oss-fuzz badge

---

include/fmt/core.h

When compiling {fmt} as a DLL, MSVC complains that we are exporting
classes that inherit from "std::runtime_error", which we are not
exporting.
In this case, it's not really a problem because that symbol is already
exported via the C++ stdlib. So we just add a pragma to silence the
warning.

Squelch MSVC warning exporting subclasses of runtime_error

---

include/fmt/core.h

Commit 3bc28fcc6b2a ("Squelch MSVC warning exporting subclasses of
runtime_error", 2019-11-29) silenced a MSVC warning under. The MinGW
compiler also defines _WIN32, but does not support the "warning" pragma.
Introduce a helper macro to squelch the MSVC warning only when using the
Microsoft compiler.
Signed-off-by: Beat Bolli <dev@drbeat.li>

Fix compilation with MinGW

---

include/fmt/core.h
include/fmt/format-inl.h

See https://github.com/fmtlib/fmt/issues/1445

Export assert_fail with FMT_API. This fixes dll build.

---

include/fmt/core.h
test/format-test.cc

I commented at the PR (https://github.com/fmtlib/fmt/pull/1342) as well but types that are convertible to `std::string_view` have ambiguous lookup after that change.
I am not sure if this is the right solution but I wanted to start the discussion here. And this change fixes the ambiguous lookup in my case.

Fix handling of types with custom formatters that are convertible to std::string_view

---

include/fmt/format.h

Extend FMT_FALLTHROUGH compatibily to gcc and clang pre-C++17

---

include/fmt/core.h
include/fmt/format.h

Based on PR #1433, which was reverted because of issue #1450 (i.e. fails to build under VS2015). This PR fixes that build while keeping the applicable warnings silenced.
VS2015 does not support the __pragma(...) syntax in the midst of a class declaration, so move it to just before the declaration.
original explanation:
> When compiling {fmt} as a DLL, MSVC complains that we are exporting classes that inherit from "std::runtime_error", which we are not exporting.
>     
> In this case, it's not really a problem because that symbol is already exported via the C++ stdlib. So we just add a pragma to silence the warning.
Successful build log:
<details>
<summary>Log</summary>
cmake -G "Visual Studio 14 2015" -Ax64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
-- CMake version: 3.15.5
-- …

Squelch MSVC warning exporting subclasses of runtime_error (fix for PR #1433)

---

README.rst

Chore(readme): use https

---

include/fmt/core.h
include/fmt/format.h

Similar to the MSC Compiler, the NVidia NVCC compiler also
emits unreachable code warnings when there is a return
statement following an exception.  These changes eliminate
those warnings.

Eliminate NVCC NVidia compiler emits unreachable code warnings

---

test/format-test.cc

Otherwise, Google Test will insist on inserting 'char8_t' NTBS into 'char' streams, but basic_ostream<char>::operator<< overloads taking 'char8_t' arguments are defined as deleted by P1423.
Handling individual 'char8_t's is done inline.
This fixes the compilation errors seen in C++20 mode beginning with VS2019 Update 2.

Convert 'char8_t' character sequences to 'char' sequences

---

include/fmt/format.h

Otherwise breaks on compilers without noexcept support

Use FMT_NOEXCEPT instead of noexcept directly

---

include/fmt/format.h

The intel-17 and intel-18 compilers seem to require that `u` be `const`:
```
/src/fmt/format.h(226): warning #437: reference to local variable of enclosing function is not allowed
char data[sizeof(u)];
```
If `u` is declared as `const auto u =1u` instead of just `auto u=1u`, the file compiles with no warnings.

Fix for older versions of intel compiler

---

include/fmt/core.h

The `std::is_base_of<T,U>()` and `std::is_reference<T>()` member functions were added in C++14.  To maintain C++11 compatibility, use the `::value` instead.
Current code fails on intel-17 and other compilers if using strict C++11

Use C++11-compatible operations

---

include/fmt/core.h

The nvcc compiler (at least up to 9.2) defines `__SIZEOF_INT128__`, but doesn't support 128-bit integers on device code:
```
error: "fmt::v6::format_arg_store<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>, char>, const char *, int, const char *>" contains a 128-bit integer, which is not supported in device code
```

Work-around for nvcc

---

include/fmt/format-inl.h

The `operator()` member function of `std::is_same` was added in C++14.  For C++11, the `::value` needs to be used instead.

Use C++11 compatible std::is_same operations

---

include/fmt/core.h

In the case of an existing `fmt` namespace (in my project this looks like `Project::fmt`) it is possible to get a namespace clash in debug builds (MSVC 2017)
When referencing `fmt` internally, be explicit that it is relative to the global namespace using `::fmt`

Avoid possible namespace clash for fmt

---

include/fmt/ostream.h

If `FMT_STATIC_THOUSANDS_SEPARATOR` defined, then locale is not included or defined, so this call will be unresolved.  I think this is the correct fix based on the code in `format-inl.h` and `format.h`

Fix so can work without locale defined

---

include/fmt/chrono.h
test/chrono-test.cc

I was getting several compiler errors when trying to format a `std::chrono::duration` to a wide string, and found that various parts of `chrono.h` had a hard dependency on narrow chars. I tried to make it agnostic as possible, and it seems to work fine for me now, although I haven't tested it with anything besides `std::chrono::duration<double, std::milli>`.
If anything needs to be changed or fixed to get this merged just let me know.

Fix formatting std::chrono::duration types to wide strings

---

include/fmt/core.h
src/format.cc

Make FMT_API symbols use the default visibility on non-Windows
platforms. Otherwise, one cannot use the generated fmt library when
compiling globally with -fvisibility=hidden.
Fixes compile errors like:
```
../3rdParty/fmt/include/fmt/core.h:757: error: undefined reference to 'fmt::v6::internal::assert_fail(char const*, int, char const*)'
```
Note that the symbol exists, but is local:
```
$ nm -C libfmtd.so.6.1.3  | grep assert_fail
U __assert_fail
0000000000233ffa t fmt::v6::internal::assert_fail(char const*, int, char const*)
```
With this patch, the compile error is gone and the symbol is properly
exported:
```
$ nm -a bin/libfmtd.so -C | grep assert_fail
U __assert_fail
00000000002366ba T fmt::v6::internal::assert_fail(char const*, int, char const*)
```
I agree that my contributions …

Fix symbol visibility on Linux when compiling with -fvisibility=hidden

---

include/fmt/core.h

since there is a const overload for data I think there should also be one for begin and end

add const begin and end overload to buffer

---

include/fmt/format.h

*begin is supposed to be different from '{' when this find is used, so we can avoid checking it.

improved use of find

---

include/fmt/format.h

The current `FMT_FORMAT_AS` macro will make `formatter<Char *>::format`
have the first argument type `const Char *&` which is incorrect an
should be `Char *const &`.  This pull request fixes that by changing the
first argument type in the macro definition body from `const Type &` to
`Type const &`.

Fix FMT_FORMAT_AS const specifier position

---

include/fmt/core.h

When building with -Werror,-Wmissing-noreturn clang identifies that assert_fail could be declared with the 'noreturn' attribute.

Add FMT_NORETURN to assert_fail prototype.

---

include/fmt/core.h
include/fmt/format.h

Previously format.h defined FMT_CLANG_VERSION after including core.h, however core.h tests FMT_CLANG_VERSION when it defines FMT_API.
format.h still defines FMT_ICC_VERSION and FMT_CUDA_VERSION, however given that core.h now defines clang/gcc/msc versions it may be worth moving that version detection into core.h too.

Move FMT_CLANG_VERSION definition to core.h

---

include/fmt/format-inl.h

In both of these commits the variables can only hold positive values and are only passed to methods that take size_t parameters.

Fix simple -Wsign-conversion cases.

---

include/fmt/format-inl.h

grisu_count_digits is only used by grisu_gen_digits, which assigns the unsigned result to a (signed) int.
Although grisu_count_digits always returns a positive integer this keeps its return type in sync with the type its result is assigned to.

Fix clang -Wsign-conversion warning in grisu_count_digits.

---

include/fmt/format.h

FMT_STRING_IMPL has an internal helper named FMT_STRING, however FMT_STRING is also the name of the macro that invokes FMT_STRING_IMPL.
Renaming this helper avoids the appearance of a recursive macro.

Fix clang -Wdisabled-macro-expansion warning from FMT_STRING_IMPL.

---

CMakeLists.txt

Passing an empty string to FMT_DEBUG_POSTFIX leads to the following error:
```
CMake Error at CMakeLists.txt:179 (set_target_properties):
set_target_properties called with incorrect number of arguments.
```
This PR fixes this.

Fix empty debug postfix

---

include/fmt/core.h

- similar to Intel and NVCC, add workaround for PGI compiler
- I tested this with:
```
kumbhar@bbpv1:~/tmp/fmt/build$ pgc++ --version
pgc++ 19.4-0 LLVM 64-bit target on x86-64 Linux -tp skylake
PGI Compilers and Tools
Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
kumbhar@bbpv1:~/tmp/fmt/build$ cmake .. -DCMAKE_BUILD_TYPE=Debug
-- CMake version: 3.15.3
-- Version: 6.1.3
-- Build type: Debug
-- CXX_STANDARD: 11
-- Required features: cxx_variadic_templates
CMake Warning (dev) at CMakeLists.txt:35 (set):
implicitly converting 'STRINGS' to 'STRING' type.
Call Stack (most recent call first):
CMakeLists.txt:253 (set_doc)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- FMT_PEDANTIC: OFF
-- Configuring done
-- Generating done
-- Build files have been …
```

Workaround for broken [[deprecated]] in PGI compiler

---

include/fmt/core.h
include/fmt/format-inl.h
include/fmt/format.h

FMT_MAYBE_UNUSED currently expands to the [[maybe_unused]] attribute on C++17.
It could be extended to previous language versions with a compiler-specific attribute if required.

Fix clang -Wunused-member-function warnings with FMT_MAYBE_UNUSED.

---

include/fmt/ranges.h
test/ranges-test.cc

Add ability to join elements of std::initializer_list

---

include/fmt/color.h
test/color-test.cc

Along with the fix I added tests that mirror their non-wide counterparts. I did NOT add tests for file writing (EXPECT_WRITE) as there doesn't seem to be an implementation using wide strings in the gtest-extra code. This is something I don't really know how to tackle, so I'd leave it up to somebody else to do.

Color formatting fixed for wide strings (fixes issue #1594)

---

include/fmt/core.h
include/fmt/format.h

Add FMT_USE_FLOAT, FMT_USE_DOUBLE and FMT_USE_LONG_DOUBLE to allow a
user of the library to configure the float types they want to allow.
This is specially useful in embedded environements where code size is
important.

Allow disabling floating point support

---

include/fmt/format-inl.h

This enables the code to properly build without errors with Clang/GCC when `-fno-exceptions` is specified.

Use FMT_THROW macro where applicable

---

include/fmt/format-inl.h

Including the ``windows.h`` file without defining ``NOMINMAX`` will define the `min()` and `max()` macros which will result in issues compiling any C++ code that uses any variant of `max`, for example `std::numeric_limits<std::streamsize>::max()` and many others.  Although max() isn't used in Fmt anywhere, it is often used in codes that include a format include file so simply upgrading to the current version of lib::fmt will break the windows build which worked prior to the update...
The fix here is pulled from the 6.1.2 release.

Avoid windows issue with min() max() macros

---

include/fmt/compile.h

Add a check that CompileFormat is derived from basic_compiled_format to avoid compilation error in case if both compile.h and format.h are included.
https://godbolt.org/z/BuhQCh

Add check for CompiledFormat to avoid ambiguous call

---

CMakeLists.txt
include/fmt/format-inl.h
include/fmt/format.h
src/format.cc
test/fuzzing/README.md

Make code properly build in fuzz mode with clang/gcc when `-fno-exceptions` is specified by using `FMT_THROW` in format files when building with FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION.
Signed-off-by: Asra Ali <asraa@google.com>

Use FMT_THROW in fuzzing build mode

---

CMakeLists.txt
support/cmake/JoinPaths.cmake
support/cmake/fmt.pc.in

It is not generally true that `CMAKE_INSTALL_<dir>` variables are relative paths:
https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files
This lead to `includedir=/nix/store/9axh4pacy7l4s7ii9j0ij54nmdslj7yy-fmt-6.2.0-dev//nix/store/9axh4pacy7l4s7ii9j0ij54nmdslj7yy-fmt-6.2.0-dev/include`.

build: Fix installation paths

---

doc/api.rst

As a bonus, this hints the user to the existence of `fmt::localtime()`/`fmt::gmtime()`.
----

Update date formatting example to use threadsafe localtime

---

include/fmt/format-inl.h

Excludes ```std::abort``` for device code only. Fixes #1659.

Exclude std::abort from compilation when compiling CUDA with Clang

---

include/fmt/format.h
include/fmt/printf.h

This fixes a few warnings I was seeing compiling with clang:
- `-Wsigned-enum-bitfield` from using standard enums in a bitfield, fixed by giving them an unsigned underlying type.
- `-Wundefined-func-template` from templates without definitions, fixed by adding `extern template` declarations.
- `-Wsign-conversion` from constructing a `string_view` with an `int` size, fixed with `internal::to_unsigned`.

Fix some warnings

---

include/fmt/format.h

- Implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20, therefore this change.
- fixes #1668

Make implicit capture explicit for C++20

---

include/fmt/core.h
test/core-test.cc

Make dynamic_format_arg_store reusable and add reserve()

---

doc/syntax.rst

syntax.html already has examples like `fmt::format("{:.{}f}", 3.14, 1)` using this, 
and https://en.cppreference.com/w/cpp/utility/format/formatter#width_and_precision shows that this is the case for the C++20 std::format
The Format Specification Mini-Language grammar seems to be the only one not showing this; update it to match.
Closes fmtlib/fmtlib.github.io#10

nested replacement fields may omit arg_id

---

include/fmt/printf.h
test/printf-test.cc

make plus flag for printf not be ignored for char argument

---

include/fmt/format.h
include/fmt/ranges.h
test/ranges-test.cc

This PR adds support to invoke `fmt::join()` on ranges that have a sentinel type that differs from its iterator type. This allows you to use `fmt::join()` on range-v3/C++20 ranges adapters. This shouldn't affect any existing code (whose sentinel is just the same as the iterator type).

Adding sentinel support to fmt::join().

---

include/fmt/chrono.h

fix max/min macro

---

include/fmt/os.h
src/os.cc

If the ``_POSIX_`` flag is set, _fdopen will not be defined by
Mingw headers, which is addressed by this PR.

Fix Mingw support

---

CMakeLists.txt

When `CMAKE_INSTALL_INCLUDEDIR` or `FMT_INC_DIR` override the header installation directory, they should be used instead of `${CMAKE_INSTALL_PREFIX}/include` in `fmt-targets.cmake` and `fmt.pc`.

Support custom FMT_INC_DIR in pkgconfig and cmake configs

---

doc/CMakeLists.txt

When building documentation sphinx creates cached files in the .doctrees
directory and aren't required for viewing documentation only for
building. As added benefit this makes fmt reprodcubile as the cached
files are different when the build environment is varied.

Don't install sphinx cache files

---

.gitignore

I'd really appreciate /doc/node_modules being ignored, as it's cluttering up a CMake super-build... Thanks.

Ignore /doc/node_modules directory

---

doc/api.rst

c++11 use formatting user-defined types

---

CMakeLists.txt

CMake Warning (dev) at /usr/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.

Move project in order to solve a CMake warning

---

include/fmt/format-inl.h

This prevents winsock2 redefinition warnings (e.g. see issue https://github.com/gabime/spdlog/issues/1589) and minimizes the stuff that windows.h includes.
I also reversed  the `#ifdef`condition to avoid redefinition warnings if either  `NOMINMAX` or `WIN32_LEAN_AND_MEAN` is already defined.

Added  #define WIN32_LEAN_AND_MEAN before including windows.h

---

CMakeLists.txt

On some platform, fmt is using the following link flag:
```cmake
target_link_libraries(fmt -Wl,--as-needed)
```
This is not supported by wasm-ld as of today.
This patch stop using it when compiling using emscripten.
Bug: https://github.com/fmtlib/fmt/issues/1736

Do not use -Wl,--as-needed with emscripten.

---

include/fmt/format-inl.h

Spelling fixes

---

include/fmt/format-inl.h

With exceptions disabled and assertions enabled FMT_ASSERT can lead to infinite recursion until stack overflows.
**Reason**
When a fmt assertion is triggered it tries to print a
message via *assert_fail* before terminating. For printing it uses
fmt::print to stderr that, when stderr output is limited leads again
to an assertion that tries to print a message (and so on).
**Reproduce**
Easiest way to reproduce is to close stderr to cause the recursion and to also close stdout to trigger an assertion condition.
Compile the following code with *FMT_EXCEPTIONS=0*:
```c++
#include "fmt/format.h"
int main() {
std::fclose(stdout);
std::fclose(stderr);
fmt::print("foo");
return 0;
}
```
Resulting stacktrace:
```
...
#35474 0x000055d68c17609f in fmt::v6::vprint (f=0x7fc5892db680 <_IO_2_1_stderr_>, …
```

Fix possible infinite recursion in FMT_ASSERT

---

include/fmt/format.h

Fix a conversion warning with Clang10 on Windows

---

include/fmt/core.h

I'm using {fmt} in not header-only mode. After upgrade to 7.0.0 build is broken due to unresolved reference.
```
error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fmt::v6::detail::vformat(class fmt::v6::basic_string_view<char>,struct fmt::v6::format_args)"
```

Fix unresolved reference error

---

fmt/format.cc
fmt/format.h

I was able to compile 4.x branch for CE6 and run a demo exmple
`fmt::print("Hello, {}!", "world");`
with the changes in this PR.
I'm not sure if the workaround for the lack of `errno` and `<cerrno>` are ok.
CE6 doesn't implement `errno`, `<cerrno>` and `strerror()` and so I return 0.
It's really useful if someone can review this PR and give impressions.

Add CE6 support

---

test/CMakeLists.txt

Autodetect MSVC static runtime

---

doc/api.rst

Documentation was a bit misleading. Many people quickly assume that fmt does compile time checks by default, while it requires the use of `FMT_STRING`. It was also unclear that `FMT_COMPILE` does the same checks.
See initial discussion here: https://github.com/fmtlib/fmt/issues/1772

Trying to clear ambiguous compile time claims

---

CMakeLists.txt
test/add-subdirectory-test/CMakeLists.txt
test/compile-error-test/CMakeLists.txt
test/find-package-test/CMakeLists.txt

Use the version range feature introduced in 3.12. On CMake <3.12 the extra dots are simply interpreted as extra version number separators.  
The fallback for ancient CMake versions is kept.

Bump tested CMake version to 3.18

---

include/fmt/core.h
include/fmt/format.h

Reduce code bloat by removing multiple instantiation of int_writer based
on the <typename UInt> parameter.
Rationale:
- The only functions that gains a speedup by int size would be
int_writer::on_dec()'s call to count_digits which uses CLZ. Thus to
still take advantage of this speedup, we store the size of the int
so we can use a switch statement to call the correct count_digits.
- All other implementations of count_digits require some sort of looping
that terminates when the value hits zero regardless of what sized int
it is.
Caveats:
- There is a performance hit when dealing with and passing around
64-bit/128-bit values compared to 32-bit values on 32-bit platforms,
and with 64-bit values on 64-bit systems. But this should not reduce the
performance that dramatically.
- There is also a …

Add FMT_REDUCE_INT_INSTANTIATIONS flag

---

include/fmt/format.h
test/ranges-test.cc

See fmtlib/fmt#1784.
Add tests that demonstrate the problem and check obvious variations.

Make join() handle non-const-only begin/end ranges

---

include/fmt/core.h

This fixes compilation error when compiling with `lcc`.
From Google:
> LCC is a compiler for Elbrus (E2K) CPU. (...) The LCC tries to mimic GCC by user interface (both supported options and GCC-specific features)
but it fails in this case: it doesn't support `__attribute__((deprecated))` for type declarations.

Disabled __attribute__((deprecated)) usage for LCC

---

doc/api.rst

Correct the locale format specifier in api.rst

---

include/fmt/core.h

clang-cl currently has a long-standing bug that using 128 bit integers generates references to symbols that are provided neither by its own nor by the Microsoft runtime: https://bugs.llvm.org/show_bug.cgi?id=25305
Visual Studio (2017, I was unable to test 2019) also does not satisfy the conditions to use 128 bit integers in {fmt}, so this effectively causes Clang to match its behavior when targetting the Microsoft ABI. The condition could therefore be simplified to just checking FMT_MSC_VER, but also checking for Clang expresses the intent better as it does advertise its support for 128 bit integers while Visual Studio does not (at the very least not in the way tested here).
This fixes the linker error described in #1798.
I agree that my contributions are licensed under the {fmt} license, …

Don't use 128 bit integers with clang-cl

---

include/fmt/format.h

PR for #1811
tested only with PGI 19.10.0 and gcc 7.5.0

fix: disabled UDL templates for PGI (#1811)

---

include/fmt/compile.h

The code snippet below generates a C4100 warning on MSVC with /W4 option:
```cpp
fmt::format(FMT_COMPILE("{}{}"), 0, "");
```
```
compile.h(371): warning C4100: '<rest_0>': unreferenced formal parameter
compile.h(382): message : see reference to function template instantiation 'const T &fmt::v7::detail::get<0,int,int>(const T &,const int &)' being compiled
with
[
T=int
]
compile.h(516): message : see reference to class template instantiation 'fmt::v7::detail::get_type_impl<0,Args>' being compiled
with
[
Args=fmt::v7::detail::type_list<int,int>
]
compile.h(516): message : see reference to alias template instantiation 'fmt::v7::detail::get_type<0,fmt::v7::detail::type_list<int,int>>' being compiled
compile.h(541): message : see reference to function template instantiation 'auto …
```

fix: warning C4100: unreferenced formal parameter

---

include/fmt/format.h

Our nvcc compilers (10.1.243 and 9.2.X) do not define the correct value for `FMT_USE_UDL_TEMPLATE` and then end up with an error later on in the build.  Explicitly search for `__NVCC__` symbol not being defined.   Might want to instead use `FMT_NVCC` or some other check, but the raw `__EDG_VERSION__` check is not working correctly for nvcc.

nvcc compiler should be EDG-based, but fails test

---

include/fmt/format.h

The intel-19 compiler warns about hidden variables:
```
/s/dev/nightly/libraries/ioss/src/fmt/format.h(2689): warning #1599: declaration hides variable "begin" (declared at line 2668)
FMT_CONSTEXPR void operator()(const Char* begin, const Char* end) {
^
detected during:
instantiation of "Context::iterator fmt::v7::vformat_to<ArgFormatter,Char,Context>(ArgFormatter::iterator, fmt::v7::basic_string_view<Char>, fmt::v7::basic_format_args<Context>, fmt::v7::detail::locale_ref) [with ArgFormatter=fmt::v7::detail::arg_formatter<fmt::v7::detail::buffer_appender<char>, char>, Char=char, Context=fmt::v7::format_context]" at line 3492
instantiation of "fmt::v7::detail::buffer_appender<Char> fmt::v7::detail::vformat_to(fmt::v7::detail::buffer<Char> &, fmt::v7::basic_string_view<Char>, …
```

Eliminate shadowed variable warnings on intel

---

CMakeLists.txt
test/format-test.cc
test/ranges-test.cc

CMakeLists.txt: Clang-warnings: removed -Wno-sign-conversion

---

include/fmt/core.h
test/format-test.cc

`buffer_appender`'s pre- and post-fix increment operators slice down to `back_inserter`, which means it actually breaks the iterator requirements (which would be actually checked in C++20, it is not `weakly_incrementable`) and also breaks any code that assumes that `++it` and `it` have the same type (as illustrated in the test case, a reduced form of how we format our optional type, which no longer compiles).

Fixing buffer_appender's ++ slicing.

---

include/fmt/format.h
test/compile-test.cc
test/ostream-test.cc

Recently I was trying to use both `FMT_COMPILE()` and struct with ostream operator, but with no luck. After first look on issues and pull requests I found one issue that describes the same problem, here it is - https://github.com/fmtlib/fmt/issues/1815. 
I'm not sure that this solution is clean enough, but I am open to change whatever you want.

Fix detail::write with fallback formatter

---

include/fmt/core.h

It seems fmt is checking cxx_override which seems to be a [CMake related term](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html). At least for clang it's  [cxx_override_control](https://clang.llvm.org/docs/LanguageExtensions.html#c-11-override-control).
In clangs current trunk fmt is reported as having no override keyword. This change silences the warning in clangs trunk as expected.

Fix usage of override for clang

---

include/fmt/chrono.h
test/chrono-test.cc

Fixes #1819
Makes dates a little easier to format:
```c++
auto the_time = std::chrono::system_clock::now();
fmt::print("{}", the_time); // the_time is converted using fmt::localtime, which then uses the normal tm formatter
fmt::print("UTC {}", fmt::gmtime(the_time)); // prints UTC time using a new overload on gmtime/localtime
```
I wanted to test localtime so I did that using setenv/tzset, though I'm not sure if that's the best way.
C++20 does include a [formatter for sys_time](https://en.cppreference.com/w/cpp/chrono/system_clock/formatter) -- in #985 it was discussed that printing a time_point was not in the standard library, but it seems with time (hah) it has now been added.
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the …

Add formatters for chrono::time_point<system_clock>

---

doc/usage.rst

The `fmt` package have been available for `build2` users for several version, see: https://cppget.org/fmt
This simply add the minimum instructions for making a `build2` project depend on it.
There are other ways to do it, but they need more understanding of `build2`.

Added build2 usage instructions.

---

include/fmt/os.h

This should allow older Linux compilers that do not have `__has_include` to use classes conditioned on the presence of the fcntl.h header.

Allow use of <fcntl.h> in Linux when __has_include is not available.

---

include/fmt/format-inl.h

Fixed mingw32/mingw64 build
```
In file included from C:\projects\gil\sample\CppLogging\modules\CppCommon\modules\fmt\src\format.cc:8:
C:/projects/gil/sample/CppLogging/modules/CppCommon/modules/fmt/include/fmt/format-inl.h:29: error: "NOMINMAX" redefined [-Werror]
In file included from C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32/bits/c++config.h:508,
from C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/cassert:43,
from C:/projects/gil/sample/CppLogging/modules/CppCommon/modules/fmt/include/fmt/format-inl.h:11,
from C:\projects\gil\sample\CppLogging\modules\CppCommon\modules\fmt\src\format.cc:8:
C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32/bits/os_defines.h:45: note: this is the location of the previous definition …
```

Fixed mingw32/mingw64 build

---

include/fmt/compile.h
test/compile-test.cc

Extends https://github.com/fmtlib/fmt/pull/1767 by adding requested test.

Add format_to_n overload that accepts FMT_COMPILE (from #1767)

---

include/fmt/format.h

1. `FMT_ALWAYS_INLINE` should imply `inline`; otherwise, there might be  linkage problems
2. Add specialization for MSVC (`__forceinline`)

Improve FMT_ALWAYS_INLINE

---

include/fmt/format.h

On MacOS and Linux the Intel compilers may be identified as the host compilers (Clang or GNU) but do not support the corresponding compiler specific fallthrough attributes. This pull request adds conditions to the preprocessor tests to skip using those in those cases.

Disable fallthrough attributes for the Intel compilers on Linux and MacOS

---

include/fmt/format-inl.h

Some small improvements that should have zero to negligible impact on the runtime.

Small improvements on Dragonbox

---

include/fmt/format.h

Changed the clz implementations to use xor instead of subtraction so that when
count_digits "undoes" the BSR -> CLZ translation, the optimizer is more
willing to recognize the equivalence.
Changed the data array in bsr2log10 to static since otherwise MSVC generates
code to build the array every time the function is called.

MSVC optimizations for count_digits

---

include/fmt/format-inl.h
test/grisu-test.cc

Fixes the issue https://github.com/fmtlib/fmt/pull/1882#issuecomment-696823912.
Sorry, it was indeed a very stupid mistake.

Fix an assertion error in Dragonbox

---

include/fmt/core.h

visual studio 2019 gives error C2049 ('fmt::v7': non-inline namespace cannot be reopened as inline) when compiling fmt with /clr)

visual studio 2019 gives error C2049 

---

include/fmt/format-inl.h

Because windows.h is full of macros (not just min and max) it is best to not include this header.
In format-inl.h we need not really much from it...

remove dependency to windows.h

---

include/fmt/format-inl.h

We don't need to incur an additional overhead on the control flow path for normal float's.

Move zero-check to an earlier branch

---

include/fmt/format-inl.h

```
fmt\include\fmt/format-inl.h(1797): warning C4018: '<=': signed/unsigned mismatch
```

Fix warning C4018: '<=': signed/unsigned mismatch

---

doc/usage.rst

Hello,
I am the author of lhelper. I am now using the fmt library is one of my project and I quickly create a recipe to download and install fmt using lhelper.
I know that lhelper is not widely used but it works quite well for C and C++ projects. It works well on Linux and on Windows where it requires the MSYS2 system. It targets the gcc and clang compilers and works well with CMake, Meson and autoconf based build systems.

Add reference to lhelper package manager in usage

---

CMakeLists.txt
include/fmt/format.h

https://github.com/fmtlib/fmt/issues/1928

Added check for `-mbig-obj` and ref qualifier check

---

include/fmt/core.h
include/fmt/format.h
include/fmt/os.h
test/core-test.cc
test/format-test.cc
test/ostream-test.cc

Make classes derived from buffer<T> final to silence the virtual destructor warning.

---

include/fmt/core.h

Detection of inline namespaces is imperfect as some compilers
don't provide __has_feature
This option allows to override it if needed.

Add option to force usage of inline namespaces

---

include/fmt/color.h
include/fmt/compile.h
include/fmt/core.h
include/fmt/locale.h

Workaround bugs in gcc 8.2/8.3 (issue #1957)

Workaround bugs in gcc 8

---

include/fmt/core.h
include/fmt/ranges.h
test/ranges-test.cc

this PR adds support for ranges when the `begin/end` members are not const. this is done by copying the range, since in those cases the range is likely to be a view, so a copy is cheap. if we want to be more restrictive, we can instead only do so when the object is `nothrow_copy_constructible`.
instead of using `begin/end` member functions, i've chosen to extend support for when they're found by argument dependent lookup, with a special case for C arrays. this is to be more consistent with the rest of the language, as the same is done for c++20 ranges and range-for loops.
an alternative to copying the range would be to forward the arguments, rather than capturing them as …

Range support

---

include/fmt/format-inl.h

Removed [-Wsign-conversion] warning in GCC

---

include/fmt/format.h
test/format-test.cc

The allocator may have a limit on the size of the allocated memory.

Allocator::max_size support in basic_memory_buffer

---

test/std-format-test.cc

Problem:
- On Apple clang 11.0.3 (clang-1103.0.32.62), pedantic mode compilation
generates the following error:
test/std-format-test.cc:114:22: error: implicit conversion changes
signedness: 'int' to 'size_t' (aka 'unsigned long')
[-Werror,-Wsign-conversion]
width_arg_id = c - '0';
~ ~~^~~~~
Solution:
- Use a `to_unsigned` to make the conversion explicit. This is
guaranteed to be safe due to the check before the ASCII-to-int
conversion.

Fix implicit signedness conversion warning

---

include/fmt/format-inl.h

fails only when FMT_BUILTIN_CTZLL is not defined

Remove accidental parenthesis

---

include/fmt/format.h

Using sizeof causes some compilers to complain:
'operand of sizeof is not a type, variable, or dereferenced pointer'
static_cast itself should be enough to silence unused variable warning

Remove sizeof from unused variable silencer

---

CMakeLists.txt
include/fmt/compile.h
include/fmt/os.h
test/chrono-test.cc
test/core-test.cc
test/format-test.cc
test/locale-test.cc
test/ostream-test.cc

Rename all shadowed types and variables and enable Wshadow when in pedantic mode

---

include/fmt/os.h
test/gtest-extra-test.cc
test/posix-mock-test.cc

If not using fcntl, but building with -Werror enabled, there's a couple functions in the tests that aren't ifdef guarded and don't actually get called. This results in the tests failing to build (log attached) due to unused function warnings.
This PR just adds them to an ifdef guard so the tests build correctly.
[blows_up.txt](https://github.com/fmtlib/fmt/files/5503811/blows_up.txt)

Fix build failure when not using fcntl with -Werror

---

.github/workflows/linux.yml

Problem:
- The version of clang to use is specified only as `clang++`. This is
inconsistent with the specifications for gcc and exposed to unexpected
failure if the default changes.
Solution:
- Specify the exact version of clang to use. I chose `clang++-9` as that
is the version that `clang++` is currently resolving to.

:art: [ci] Specify the exact version of clang to use

---

include/fmt/printf.h

This is the same change as in the closed pull request https://github.com/fmtlib/fmt/pull/1853 but this time with a simple microbenchmark to argue for it. I hope this isn't considered impolite.
The change starts to be noticeable at a format string length of about 100 characters.
The microbenchmark is the same as in https://github.com/fmtlib/fmt/pull/1982:
```c++
#include <benchmark/benchmark.h>
#include <fmt/printf.h>
void long_argument(benchmark::State& state) {
std::string long_string(state.range(0), 'A');
for (auto _ : state) {
benchmark::DoNotOptimize(fmt::sprintf("%s", long_string));
};
}
BENCHMARK(long_argument)->Arg(10)->Arg(100)->Arg(1000)->Arg(10000);
void …
```

use memchr for searching for '%' in printf format string

---

include/fmt/os.h

fix gcc warning of missing override

---

test/format-test.cc

Problem:
- gcc-10 is generating the following warning at all standards:
test/format-test.cc: In member function 'virtual void UtilTest_BitCast_Test::TestBody()':
test/format-test.cc:108:42: error: useless cast to type 'uint64_t' {aka 'long long unsigned int'} [-Werror=useless-cast]
108 |   s = fmt::detail::bit_cast<uint32_pair>(uint64_t(~0ull));
|                                          ^~~~~~~~~~~~~~~
- gcc-8 is generating the following warning at all standards:
test/format-test.cc: In member function 'virtual void UtilTest_BitCast_Test::TestBody()':
test/format-test.cc:108:56: error: useless cast to type 'uint64_t' {aka 'long long unsigned int'} [-Werror=useless-cast]
s = fmt::detail::bit_cast<uint32_pair>(uint64_t(~0ull));
^
Solution:
- Cast 0 to a 64 unsigned bit int and then invert. …

:wrench: Silence useless cast warnings

---

include/fmt/compile.h

Problem:
- On Apple clang version 11.0.3 (clang-1103.0.32.62) in C++17 and C++20
mode, clang 11.0.0 in C++17 and C++20 mode, and clang 9.0.1 in C++17
mode, the following error is generated:
In file included from test/compile-test.cc:16:
include/fmt/compile.h:518:25: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
return {f, pos + (end - str.data()) + 1, ctx.next_arg_id()};
~  ~~~~^~~~~~~~~~~~
include/fmt/compile.h:538:31: note: in instantiation of function template specialization
'fmt::v7::detail::parse_specs<int, char>' requested here
constexpr auto result = parse_specs<id_type>(str, POS + 2, ID);
^
include/fmt/compile.h:569:17: note: in instantiation of function template specialization …

:bug: Implicit sign conversion warning in clang in c++17 and 20 modes

---

include/fmt/printf.h
test/printf-test.cc

This affects the performance of fmt::sprintf in the case where the format string is at least on the order of 100 characters long.
The benchmark:
```c++
#include <benchmark/benchmark.h>
#include <fmt/printf.h>
void long_printf_format_string(benchmark::State& state) {
std::string format_string = std::string(state.range(0), 'A') + "%s";
std::string message = "Hi";
for (auto _ : state) {
benchmark::DoNotOptimize(fmt::sprintf(format_string, message));
};
}
BENCHMARK(long_printf_format_string)->Arg(10)->Arg(100)->Arg(1000)->Arg(10000);
void long_fmt_format_string(benchmark::State& state) {
std::string format_string = std::string(state.range(0), 'A') + "{}";
std::string message = …
```

Printf get container

---

test/std-format-test.cc

Problem:
- gcc-8 gives the following error when compiling this function on all
standards:
```
test/std-format-test.cc: In member function 'constexpr auto std::formatter<S>::parse(std::format_parse_context&)':
test/std-format-test.cc:112:17: error: call to non-'constexpr' function 'int isdigit(int)'
if (!isdigit(c) || (++iter, get_char()) != '}')
~~~~~~~^~~
```
Solution:
- Write a `constexpr` version of `isdigit` for use in this function.

:bug: Cannot call non-constexpr function in constexpr context

---

include/fmt/chrono.h
include/fmt/color.h
include/fmt/format-inl.h
test/format-test.cc

Update a few internal calls to fmt::format to use FMT_STRING, improving compatibility with the FMT_ENFORCE_COMPILE_STRING compile option.

Always use FMT_STRING internally where possible [Issue #2002]

---

.gitignore
support/build.gradle

[Last month(2020/10), there was Android Studio 4.1 release](https://android-developers.googleblog.com/2020/10/android-studio-41.html), this PR targets that. 
Adjust for the IDE (Android Studio)
* Gradle 5.x -> 6.6.1
* Android Gradle Plugin 3.x -> 4.1.1
* Android NDK `21.3.6528147`
NDK version is not mandatory. Users can comment the line, and use their own.
The build step is not changed.
```bash
pushd support # this folder has build.gradle
gradle assemble
popd
tree -L 2 ./libs
```
ignore `.cxx` which was `externalNativeBuild` in old Android Gradle Plugin versions
`build.gradle` file now uses variable `rootDir` instead of using the relative path to make ease of understanding.
```console
user:host$ pushd support/
~/dev/fmt/support ~/dev/fmt
user:host$ gradle assemble
> Configure project : …
```

Update build.gradle for latest AGP

---

.github/workflows/windows.yml

Problem:
- Both Windows builds test C++14
Solution:
- Use C++11 for `windows-2016` builds and C++14 for `windows-2019`
builds.

:new: [CI] Test with C++14 in Windows 2019

---

include/fmt/compile.h
test/compile-test.cc

Right now {fmt} cannot be used with empty string format with compile-time API, while it can be used with regular API:
```cpp
fmt::format(""); // ok
fmt::format(FMT_COMPILE("")); // compilation error
```
Proof on [Compiler Explorer](https://godbolt.org/z/6Yj38a)
With this tiny fix, compile-time API also get this useless feature.
Also, a test for `FMT_COMPILE` with an empty string added.

Fix formatting with compile-time API when format string is empty

---

test/compile-test.cc

Extends #2019 by simplifying tests. This change was requested there https://github.com/fmtlib/fmt/pull/2019#discussion_r532121123 but I didn't manage to simplify it.
Turns out that the position in `EXPECT_EQ` macro is the key:
```cpp
EXPECT_EQ(test_format<5>(FMT_COMPILE("{}"), true), "true"); // compilation error
EXPECT_EQ("true", test_format<5>(FMT_COMPILE("{}"), true)); // ok
```
In this PR arguments are just swapped, so the result is the first argument. Just like all over the file:
https://github.com/fmtlib/fmt/blob/5a493560f59369e9fa664e8945b8e8a8ec4391b2/test/compile-test.cc#L125-L136

Simplify CompileTimeFormattingTest tests by reordering arguments of EXPECT_EQ

---

README.rst
doc/api.rst
doc/index.rst
doc/syntax.rst
doc/usage.rst

docs: use https for some links

---

include/fmt/compile.h
test/compile-test.cc

Right now {fmt} has a special macro to invoke compile-time API functions - `FMT_COMPILE`. This macro can be replaced with UDL for modern compilers that support C++20. The chosen name in this PR for this feature is `_cf`.
```cpp
fmt::format(FMT_COMPILE("{}"), 42); // 🙁 not modern
fmt::format("{}"_cf, 42); // 🙂 modern as hell
```
Note that only GCC 9.3+ support that. Clang (trunk) is also able to compile this code, but it doesn't have `__cpp_nontype_template_parameter_class` defined, I hope it'll be fixed in Clang 12 release.
Proof on [Compiler Explorer](https://godbolt.org/z/boTTr9)
`constexpr` is used instead of `consteval` (even though it would make more sense) to lower GCC version.
Also, I should note that this PR is based on my own ideas and the following comments: …

Add UDL as replacement for FMT_COMPILE

---

include/fmt/format.h
test/ostream-test.cc

Reenable support for fallback formatter to join (#2040)

---

include/fmt/ostream.h

Since gcc 9 it warns about is_streamable to have only private methods.

Suppress gcc warning on privates-only class

---

include/fmt/os.h
test/os-test.cc

Fix compile error when using `fmt::join(...)` as an argument to `fmt::ostream::print(...)`.

Forward arguments to work with views

---

include/fmt/chrono.h

Disable warning about format string

---

include/fmt/format.h

While trying to build fmtlib with EASTL, I realized that `cwchar` was missing:
```
include/fmt/format.h:3964:7: error: no member named 'fputws' in namespace 'std'; did you mean simply 'fputws'?
if (std::fputws(buffer.data(), f) == -1)
```

Add cwchar to format.h for std::fputws

---

include/fmt/compile.h
include/fmt/core.h
include/fmt/format-inl.h
include/fmt/format.h
test/compile-test.cc

Extends https://github.com/fmtlib/fmt/pull/2019 by adding support of formatting specs for bool, integer, char and string:
- [fill](https://fmt.dev/latest/syntax.html#grammar-token-fill) `<a character other than '{' or '}'>`, like `{:*>4}`, `{:ж^4}`
- [align](https://fmt.dev/latest/syntax.html#grammar-token-align) `"<" | ">" | "^"`, like `{:^4}`
- [sign](https://fmt.dev/latest/syntax.html#grammar-token-sign) `"+" | "-" | " "`, like `{:+}`
- `"#"`, like `{:#b}`
- `"0"`, like `{:04}`
- [width](https://fmt.dev/latest/syntax.html#grammar-token-width) `integer | "{"  "}"`, like `{:4}`, `{:{}}`
- [int_type](https://fmt.dev/latest/syntax.html#grammar-token-int_type) `"b" | "B" | "d" | "o" | "x" | "X"`, like `{:b}`, `{:x}`, `{:X}`.
I think that bool, integer, char and string formatting should be …

Add support of most format_specs for formatting at compile-time

---

include/fmt/format.h
test/compile-test.cc
test/format-test.cc

Right now formatting of `std::byte` using compile-time API like so:
```cpp
fmt::format(FMT_COMPILE("{}"), std::byte{42})
```
ends up with compilation error, [proof on Compiler Explorer](https://godbolt.org/z/5xqrvr). Because there are 2 `write` functions which satisfy for the passed type `std::byte`:
https://github.com/fmtlib/fmt/blob/5a37e182deee09a873777ff3f8e901d117e5f39b/include/fmt/format.h#L2114-L2120
https://github.com/fmtlib/fmt/blob/5a37e182deee09a873777ff3f8e901d117e5f39b/include/fmt/format.h#L2150-L2162
Also, I found `__cpp_lib_byte` feature macro, so all new checks are based on this macro instead of `__cplusplus >= 201703L` and I changed old checks accordingly.

Fix std::byte formatting with compile-time API

---

include/fmt/chrono.h
include/fmt/color.h
include/fmt/core.h
include/fmt/format.h
test/format-test.cc

As it was discussed here - https://github.com/fmtlib/fmt/pull/2056#discussion_r542988874, an fallback to the `inline` inside `FMT_CONSTEXPR(20)` macro definitions is not always a good solution. Especially when `FMT_CONSTEXPR(20)` macro should be used together with `FMT_INLINE` macro, in C++11 they both expand to `inline` specifier.
In this PR I removed that fallback to `inline` and placed `inline` specifiers where it's needed (for non-template, not member or friend defined in class/struct/union functions), so everything should stay the same in C++11. When `FMT_CONSTEXPR(20)` is expanded to `constexpr` all these manually-tuned functions will have `constexpr inline` specifiers, which is okay.

Remove fallback to inline specifier from FMT_CONSTEXPR(20) macro

---

doc/syntax.rst

Thank you for this awesome library, I was just reading the documentation until I've noticed this little typo.
tm_mon is supposed to be 8 here.

Correct a typo on syntax.rst (documentation)

---

CMakeLists.txt

The build variable FMT_MASTER_PROJECT is added so user can build and install fmt library even if the project is included as a submodule. See discussion: #2098.
The PR is slightly updated to address two change requests.

Add build variable: FMT_MASTER_PROJECT

---

include/fmt/ranges.h

This is a minor fix for an issue I discovered in one of my own projects that for some reason I cannot seem to reproduce it in ranges-test.cc. I'm not sure *why* exactly this isn't having any troubles internally, but it does definitely appear to be invalid syntax.

Add missing detail namespace

---

include/fmt/format.h
test/format-test.cc

I am contributing for the first time.

Add support for the s format specifier to bool (#2094)

---

.github/workflows/linux.yml
include/fmt/format.h

Somehow I missed that `ubuntu-18.04` image on CI has GCC-10._**1**_ installed, so CI is unable to build compile-time formatting tests because they require GCC-10._**2**_+. 
https://github.com/fmtlib/fmt/blob/9c418bc468baf434a848010bff74663e1f820e79/include/fmt/format.h#L286-L287
https://github.com/fmtlib/fmt/blob/9c418bc468baf434a848010bff74663e1f820e79/test/compile-test.cc#L190-L191
So I just switched the Ubuntu image to `ubuntu-20.04` for the `g++-10` compiler with C++20 standard. The `CompileTimeFormattingTest` tests do run now, it's checked by failing CI build with [false commit](https://github.com/alexezeder/fmt/commit/7568ddc94cb11957ea1cf64dc0e2841692998f3e) on [CI](https://github.com/fmtlib/fmt/runs/1754041007?check_suite_focus=true).
Also, this PR fixes the problem that was not …

Use gcc-10.2 instead of gcc-10.1 on CI, also fix one problem

---

include/fmt/compile.h

-----------
Fixes #2116 (for me, for now!)
Please do note that I am no expert in compile-time metaprogramming, therefore this patch might be "wrong", although it did work out for me.

fix #2116 (FMT_COMPILE throws unmatched '{' on ESP32)

---

include/fmt/format.h
include/fmt/ranges.h
test/ranges-test.cc

I noticed here this strange check:
https://github.com/fmtlib/fmt/blob/acef0bb51ade288bf7930d1b74d1338f49f9f900/test/ranges-test.cc#L16-L18
So I decided to do it right - by using `__cpp_if_constexpr` feature macro. But later I realized that since there is no mention in docs that ranges are supported only with C++14 (or C++17 because of `constexpr if`) it's strange to me that test doesn't check C++11, especially when this check is not necessary at all with only few changes in the test.
With this PR `ranges-test` compiles with C++11 on probably most ancient supported compilers - gcc-4.8 and clang-3.5 (couldn't test 3.4).

Make ranges-test available with C++11

---

CMakeLists.txt

the library itself needs to be installed before
the fmt-targets.cmake file is installed,
otherwise the installed targets file doesn't
actually point to the library using
IMPORTED_LOCATION

Fix ordering of install commands for CMake

---

doc/api.rst
include/fmt/format.h
test/format-test.cc

Passing a function pointer to fmt::ptr results in:
In file included from /home/mac/git/fmt/test/gmock/gmock.h:238,
from /home/mac/git/fmt/test/format-test.cc:31:
.../fmt/test/format-test.cc: In member function ‘virtual void FormatterTest_FormatPointer_Test::TestBody()’:
.../fmt/test/format-test.cc:1486:56: error: no matching function for call to ‘ptr(void (&)(int, double, std::__cxx11::string))’
format("{}", fmt::ptr(function_pointer_test)));
Let's add an overload to support that usage.

fmt::ptr: Support function pointers

---

include/fmt/chrono.h
include/fmt/compile.h
test/compile-test.cc

Compile-time API functionality extended to support manual ordering and named arguments. Unlike my first attempt to do this in https://github.com/fmtlib/fmt/pull/2111, where I tried to use a format part array, here I'm just reusing that recursion of functions `compile_format_string()` and `parse_tail()`.
Some points for the changes:
* works with C++17 as it did before
* unlike https://github.com/fmtlib/fmt/pull/2111, this PR fully supports custom parsing in formatters
* manual indexing with `{0}` and automatic indexing with `{name}` work exactly as they work in the runtime API
* a switch of the argument indexing between automatic to manual or manual to automatic is detected at compile-time, and `static_assert`s fail with corresponding messages
* usage of named arguments with specs is …

Add full support of format string parsing in compile-time API

---

include/fmt/format.h

Fixes https://github.com/fmtlib/fmt/issues/2140.
Some points:
- legacy Clang (prior to 7.0) treats function pointers also as `const T*` pointers but unable to convert them
- some GCC versions decay function pointers to `const void*`, exactly like MSVC does
- `inline` specifiers removed because all functions are templates

Fix `fmt::get` with function pointers for some GCC versions and legacy Clang

---

include/fmt/format.h

Currently, if exception is disabled, an error in `fmt` will result a termination via `FMT_ASSERT`, but there is no error message printed on `stderr`, so it can be a little bit confusing for the user on why the program failed.
This PR modifies `FMT_THROW` to pass `exception.what()` to `FMT_ASSERT` as the error message.
Although it doesn't provide more information which part of format string caused the error, it is better than printing no error message at all.
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

Print error message in FMT_THROW when exception is disabled

---

include/fmt/core.h

Fixes https://github.com/fmtlib/fmt/issues/2149.
This PR moves a special `void_t` workaround for GCC 4.x:
https://github.com/fmtlib/fmt/blob/640acba8509d7458a9c749b243355d223b1cfa25/include/fmt/core.h#L1382-L1385
under the GCC < 5.0 macro check, adding a straightforward `void_t` implementation:
```cpp
template <typename...> using void_t = void;
```
for other compilers.
This solves the problem with GCC 8.x that fails with the current implementation of `void_t`.

Use simplified void_t for all compilers except GCC 4.x

---

include/fmt/compile.h
test/compile-test.cc

Right now, when {fmt} fails to prepare compiled format for format string (using `FMT_COMPILE` or `_cf`) it also fails to report about that clearly. Here is an example - https://godbolt.org/z/G1ETdc.
There [were](https://github.com/fmtlib/fmt/pull/2061) some attempts to make the error a bit clearer, but as it [turned out](https://github.com/fmtlib/fmt/pull/2061#issuecomment-743775046) {fmt} should fall back to the runtime API in those cases. This PR adds that fallback.
Some points for the PR:
* test added
* there is a bit of code duplication introduced, because I decided that this code is clearer:
```cpp
#ifdef __cpp_if_constexpr
if constexpr (std::is_same<remove_cvref_t<decltype(compiled)>,
detail::unknown_format>()) {
return format(static_cast<basic_string_view<typename …
```

Fix fallback to runtime API from compile-time API

---

include/fmt/format-inl.h
test/test-assert.h

This commit replaces use of the assert() macro in format-inl.h with
FMT_ASSERT(). This allows us to drop the cassert include.
Note that the change to ``FMT_ASSERT`` in test-assert.h is to avoid the following warning:
```
In file included from /home/jscott/src/fmt/test/format-impl-test.cc:10:
/home/jscott/src/fmt/include/fmt/format-inl.h: In destructor ‘fmt::v7::detail::bigint::~bigint()’:
/home/jscott/src/fmt/test/test-assert.h:26:52: warning: throw will always call terminate() [-Wterminate]
26 |   if (!(condition)) throw assertion_failure(message);
|                                                    ^
/home/jscott/src/fmt/include/fmt/format-inl.h:1300:15: note: in expansion …
```

Don't include <cassert>. (#2148)

---

include/fmt/format.h
test/format-test.cc

Make truncating_iterator an output_iterator

---

include/fmt/compile.h
include/fmt/core.h
test/compile-test.cc

Resolves https://github.com/fmtlib/fmt/issues/2141.
All useful info can be found in the issue, including code examples.
One small detail for this PR - `fmt::formatted_size()` in `compile.h` becomes templatized too to eliminate one unclear case - https://godbolt.org/z/Yxnccj. In few words, the implementation of `fmt::formatted_size()` for runtime API (non-compiled format string) changes depending on whether we include `fmt/compile.h` or not. You can see it in assembly for the `formatted_size`, it uses `counting_iterator`, which is used in the overload from `compile.h`:
https://github.com/fmtlib/fmt/blob/835b910e7d758efdfdce9f23df1b190deb3373db/include/fmt/compile.h#L837-L840
but not in the overload from `core.h`:
https://github.com/fmtlib/fmt/blob/835b910e7d758efdfdce9f23df1b190deb3373db/in …

Fix fmt::formatted_size() with compiled format (FMT_COMPILE) as argument

---

include/fmt/compile.h

Resolves https://github.com/fmtlib/fmt/issues/2170.
I checked this fix on GitHub Actions for GCC 6-10 for warning from issue:
| | GCC 6 | GCC 7 | GCC 8 | GCC 9 | GCC 10 |
|-|-|-|-|-|-|
|before| [no warning](https://github.com/alexezeder/fmt/runs/2100340626?check_suite_focus=true#step:4:1) | [warning presented](https://github.com/alexezeder/fmt/runs/2100340632?check_suite_focus=true#step:4:1) | [warning presented](https://github.com/alexezeder/fmt/runs/2100340641?check_suite_focus=true#step:4:1) | [warning presented](https://github.com/alexezeder/fmt/runs/2100340646?check_suite_focus=true#step:4:1) | [no warning](https://github.com/alexezeder/fmt/runs/2100340651?check_suite_focus=true#step:4:1) |
|after | [no warning](https://github.com/alexezeder/fmt/runs/2100353102?check_suite_focus=true# …

Workaround a GCC 7,8,9 warning about unused but set parameter

---

include/fmt/format.h

Avoid one unneeded empty loop pass, e.g. with
`std::string message = fmt::sprintf("The answer is %d", 42);`
(mostly if % placeholder is at the beginning or end of the string to be formatted)

optimize append

---

include/fmt/format.h

Fix MSVC /clr builds

---

include/fmt/core.h

Since the changes of 1305cbeb (Fix MSVC2019 error C2049 when compiling
with /clr (#1897), 2020-09-23), compiling fmt with MSVS 2019 resulted in
fmt\include\fmt\core.h(180,32): warning C4668: '_MANAGED' is not defined
as a preprocessor macro, replacing with '0' for '#if/#elif'.
when the (disabled by default) warning C4668 was enabled.
Fix this simply by checking if _MANAGED is defined before testing it.
---

Fix harmless MSVS warning about using undefined _MANAGED symbol

---

include/fmt/format.h

Adding default case for switch statements where the compilation
flag -Wswitch-default is present on the command line when spdlog
is included in external projects.
Signed-off-by: Ryan Sherlock <ryan.m.sherlock@gmail.com>

add default cases

---

.github/workflows/windows.yml
test/CMakeLists.txt

- Fix C++17 Visual Studio builds.
- Use C++17 for `windows-2019` builds.
- Removed options for unsupported compiler (MSVC11).
- Removed options, not needed after enabling C++11+ features in gmock/gtest.

Fix C++17 build

---

include/fmt/core.h

This works around a compiler bug in xlc when the file is preprocessed by nvcc.  This manifests as `format_arg_store::desc` being undefined at link time.  Pulling out the `detail::encode_types<Context, Args...>()` into it's own line was the fix.
If you prefer to have this fixed in another way, I am open to suggestions.
More information here:
https://github.com/LLNL/axom/pull/492
Write up about the minimal compiler reproducer by @joshessman-llnl:
So I was initially just looking to how minimally the behavior we were seeing with fmt could be reproduced, and was able to get to this:
```
constexpr int get_bar()
{
return 0;
}
struct Foo
{
// static constexpr int bar = 0; // Works …
```

Work around xl compiler bug when nvcc preprocesses this file

---

include/fmt/os.h
test/os-test.cc

Fix: fmt::ostream cannot be moved while holding buffered data #2197

---

.github/workflows/linux.yml
include/fmt/os.h

Add speech synthesis support to {fmt}.
For example:
```c++
#include <fmt/os.h>
int main() {
fmt::say(
R"SHANTY(
There [[emph +]] once was a pen that [[emph +]] put to [[emph +]] paper,
It [[emph -]] was [[emph +]] gonna be written [[emph +]] sooner or later,
Ctrl-S went down, the proposal sent out,
Vote [[emph +]] down my committee vote [[emph +]] down.
[[emph +]] Soon, may the Unicode come,
So [[emph +]] we can write aleph and [[emph +]] xĭ and [[emph +]] từng,
One day when '23 is done,
We'll take our bom and go.)SHANTY");
}
```
Output:
https://user-images.githubusercontent.com/576385/113313097-c9623f00-92bf-11eb-8903-f7acaa7c982f.mov

Add speech synthesis support

---

include/fmt/core.h
test/format-test.cc

Make buffer_appender default-constructible when back_insert_iterator is

---

include/fmt/format.h

Resolves #2205, at least compile-time part of it.
A newer version of Clang should probably be used on CI to eliminate potential problems with compile-time tests in the future.

Specify size for `prefixes` static data

---

include/fmt/format.h

I noticed a static initializer was introduced by the fmt library in our binary. It was attributed to:
[include/fmt/format-inl.h#L387](https://github.com/fmtlib/fmt/blob/95da4847274c42c110fd5bf1bf61d3f94be4a08e/include/fmt/format-inl.h#L387).
This can be avoided by making the uint128_wrapper constexpr.

constexpr uint128_wrapper

---

test/chrono-test.cc

add a pre-check of _CRT_SECURE_NO_WARNINGS before the def

Suppress redef warning of _CRT_SECURE_NO_WARNINGS if any.

---

test/format-test.cc

Try to suppress MVSC warn of narrowing at
> fmt\test\format-test.cc(774): warning C4838: conversion from 'int' to 'wchar_t' requires a narrowing conversion

Try to suppress MVSC warn of narrowing

---

include/fmt/format.h
include/fmt/ranges.h
test/ranges-test.cc

Fixes formatting ranges into wide strings

Ranges wide strings support

---

include/fmt/format.h

Name lookup within exported templates cannot find non-exported entities by ADL when instantiation takes place outside the module.

Use qualified name lookup rather than ADL.

---

include/fmt/chrono.h
include/fmt/color.h
include/fmt/compile.h
include/fmt/core.h
include/fmt/format.h
include/fmt/locale.h
include/fmt/ostream.h
include/fmt/printf.h
include/fmt/ranges.h

Start by tagging official API for module export

Support compiling {fmt} as named module

---

include/fmt/core.h
include/fmt/format.h
src/format.cc

This should fix https://github.com/fmtlib/fmt/issues/2228
The issue is caused by changes in clang below.
[MinGW] Fix dllexport of explicit template instantiation
by mstorsjo on Apr 25 2019
https://reviews.llvm.org/D61118
Have to keep seperated `dllexport` marking points, until `msvc` follows `GNU` and `LLVM`'s policy or vice versa.

Create separate dllexport marking points for clang and msvc.

---

include/fmt/chrono.h

As per discussed and requested on #2238.
Tested on VS 2019 + WSL Ubuntu 20.04.

Appending a space to guarantee non-empty strftime() result.

---

include/fmt/compile.h
test/compile-test.cc

Without this fix, `udl_compiled_string` works only for char types that have a 1-byte size.

Fix udl_compiled_string with non-byte chars (e.g. wchar)

---

include/fmt/color.h
include/fmt/core.h
include/fmt/format.h

Discussion: https://github.com/fmtlib/fmt/pull/2243#discussion_r616803322

C++17: std::char_traits<>::{compare,length} is constexpr.

---

include/fmt/core.h
include/fmt/ostream.h
include/fmt/printf.h
src/fmt.cc

To compile {fmt} as named module, there must be at least the source provided with the (primary) module interface.
I chose the most elegant and probably the most desirable implementation strategy: a single-file module with a private module partition. This has these benefits:
- easiest to use
- the existing headers require no changes other than providing macro hooks for the exported entities (if implemented cleanly)
- all macros are available during compilation and require no further attention
- the existing source parts all go into the non-exported, unreachable private module partition, which is basically a module implementation unit that's directly fused to end of the module interface unit
- there are only 2 artefacts created:
1. the object file
2. the built module interface (BMI)
The …

Provide a module interface unit

---

include/fmt/compile.h
include/fmt/core.h
include/fmt/format.h
test/compile-test.cc

This PR makes the name of named arguments created via `_a` literal be available at compile-time. So named arguments can be checked at compile-time now exactly like non-named ones. 
I haven't implemented these checks for `FMT_STRING`, but I did it for compile-time API. Thus these lines:
```cpp
fmt::format(FMT_COMPILE("{0}"), 42);
fmt::format(FMT_COMPILE("{arg}"), "arg"_a = 42);
```
produce the same compiled format, so it's zero-overhead for arguments naming. Of course, `fmt::arg(name, value)`-based named arguments still have this overhead because they cannot provide their names at compile-time. Here are [the results](https://github.com/alexezeder/fmt_bnchmrk/tree/feature/named_args):
| Benchmark                         |    Time     |       CPU | Iterations |
| …

Compile-time named arguments

---

.github/workflows/windows.yml
include/fmt/core.h
include/fmt/format.h

More info here - https://github.com/fmtlib/fmt/pull/2240#discussion_r618631034
Also, `FMT_CONSTEXPR_CHAR_TRAITS` was fixed for MSVC and two C++20 MSVC configurations were added to CI:
* x64, Debug
* x64, Release

Use proper check for non-type template parameters

---

include/fmt/format-inl.h
include/fmt/format.h

applies to exception classes in case of msvc only

Keep defaulted destructors inline

---

include/fmt/core.h

Fixed my mistake in the previous patch.
Fix for Microsoft Visual Studio and clang/libc++ < 4.0.
Discussion: https://github.com/fmtlib/fmt/pull/2246#issuecomment-827184981
Links:
https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-150
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-150
https://libcxx.llvm.org/docs/Cxx1zStatus.html

C++17: std::char_traits<>::{compare,length} is constexpr - v2

---

include/fmt/format.h

Bring `detail::find()` into scope.

Make wchar_t overloads usable in module

---

include/fmt/os.h
test/os-test.cc

Discussion: https://github.com/fmtlib/fmt/issues/2269

Add a formatter specialization for std::error_code.

---

include/fmt/os.h
src/os.cc
test/os-test.cc
test/posix-mock-test.cc

See: https://github.com/fmtlib/fmt/issues/2274

Fix issue #2274.

---

include/fmt/compile.h

Unqualified calls to `make_format_args` may find the same name by ADL in `<format>` if this C++20 header happens to be directly or indirectly included in a translation unit. Do a qualified lookup instead.

Prevent ambiguity in name lookup

---

include/fmt/compile.h
include/fmt/core.h
include/fmt/format.h
test/format-test.cc

Possible with this PR and a compiler with non-type template arguments support:
```cpp
fmt::format(FMT_STRING("{foo}{bar}"), "bar"_a = "bar", "foo"_a = "foo");
"{foo}{bar}"_format("bar"_a = "bar", "foo"_a = "foo");
```
Still impossible:
```cpp
fmt::format(FMT_STRING("{foo}{bar}"), fmt::arg("bar", "bar"), fmt::arg("foo", "foo"));
```
```
/fmt/include/fmt/core.h:2310:39: error: static assertion failed: use statically named arguments with compile-time format strings: fmt::arg("name", value) -> "name"_a = value
```

Add support for statically named arguments with `FMT_STRING`

---

src/os.cc

Visual Studio was complaining about unreachable code, presumably because vwindows_error was throwing the std::system_error instead of returning. Not 100% confident this is the correct fix, but quickly taking a look at how the function is used, this seems like the intended behavior.

Fix Visual Studio warning

---

include/fmt/core.h

Warning C4100 may cause compile failures under strict warning regimes.

Silence msvc warning about an unused named parameter

---

include/fmt/core.h

This PR resolves the issue mentioned in #2295 caused by a clash in the lookup between the `STL` shipped in vs2019 preview 4 (16.10) and `fmt`.
There's several other unqualified lookups to that function in particular, but as I didn't notice any causing issues I left them alone. If that changes I'll make a new PR to deal with them.

fix compile error on msvc preview 4 (16.10) involving lookup clash

---

.github/workflows/linux.yml
.github/workflows/macos.yml
include/fmt/core.h
include/fmt/format.h
include/fmt/os.h
src/format.cc

When compiling with `-fvisibility=hidden`, linker errors occur because a symbol was not marked as being exported. The `final` keyword is not necessary for a class that is already marked as `final`.
How to reproduce:
```bash
CXXFLAGS=-fvisibility=hidden cmake -S . -B build/ -DBUILD_SHARED_LIBS:BOOL=ON -GNinja
cmake --build build/
```
[Log output](https://github.com/fmtlib/fmt/files/6504551/log.txt)

export missed symbol

---

include/fmt/core.h

Microsoft's constexpr evaluator treats the type of micro[0] and micro[1] as
plain char, and so sign extends before comparing them to ints.
The normal compiler, including the optimizer, does not fail in this way,
so this is merely a "future proof" change in case someone uses is_utf8()
in a constant expression.

Avoid unwanted sign extensions from MSVC in is_utf8.

---

CMakeLists.txt

Enable  `-fvisibility=hidden` and `-fvisibility-inlines-hidden` by default in `CMakeLists.txt`. Reduces the size of the shared library from 244K to 212K. Allow users to override the default choice.
Related to #2299.

cmake: hide private symbols by default

---

doc/syntax.rst

Documents that the 'c' type is a valid type for integer types. Since
boolean uses the same types as integer its documentation is
automatically updated.

Update integer presentation types documentation.

---

include/fmt/compile.h
include/fmt/format-inl.h
include/fmt/format.h
test/compile-test.cc

Resolves https://github.com/fmtlib/fmt/issues/2280.
By adding a new exported function - `detail::print_buffer(std::FILE*, const memory_buffer&)`. This function is used in both `vprint()` from `format-inl.h` and a new `print()` from `compile.h`.

Add `fmt::print()` overload to support compiled format (`FMT_COMPILE`)

---

include/fmt/os.h
include/fmt/printf.h

Latest MSVC 16.10.0 introduced a function std::make_format_args which clashes with fmt::v7::make_format_args.
This means that all calls to make_format_args need to by qualified to avoid ADL clash

qualify make_format_args

---

include/fmt/core.h
include/fmt/format.h
test/format-test.cc

Fixes #2305.
Is there a better way to check for the `0`-padding-option than what I wrote?

Ignore zero-padding for non-finite floating points

---

include/fmt/format.h
test/format-test.cc

Fixes #2308 
If this change to `write_bytes` isn't desired, the calling code could be changed to directly calling `write_padded<align::right>` with the lambda copied from `write_bytes`.

Align hex floats right as default

---

test/CMakeLists.txt
test/module-test.cc

Most of the API of core.h, format.h, and args.h
Just narrow strings. Tests for wide strings will come later.

More module tests

---

include/fmt/format.h

This fixes compiling `fmt::formatted_size(L"{}", 42)`.

Enable `Char` types other than `char`

---

test/module-test.cc

My additional tests (not yet published) for non-`char` overloads didn't need action 😁

Swap parameter order to match #2327

---

include/fmt/chrono.h
include/fmt/core.h

And allow lookup of non-exported names from local classes in function templates.
Using declarations link these names into the body and make them available for name-lookup when the local classes are instantiated together with the function bodies that contain them.

Use qualified name-lookup in module.

---

include/fmt/core.h
include/fmt/format.h
test/compile-test.cc

By reading the changelog for upcoming release, I realized that it does not mention one of the major breaking change of custom formatters for compile-time formatting - `const`-qualified `format` method, so I decided to check how do custom formatters work at compile-time and realized that they actually don't work.
There are 3 commits, by the complexity of changes from the commit that just fixes the library, to the commit that adds dynamic width handling for the `test_formattable` class in compile-test.cc. The latter two can be removed or squashed into the first one, on demand. This time I cannot [use custom formatters](https://github.com/fmtlib/fmt/pull/2129#discussion_r575826176) from `chrono.h` because they use `memory_buffer` and it's not ready to be used at compile-time yet.

Fix `FMT_COMPILE()` with custom types

---

src/fmt.cc
test/CMakeLists.txt
test/module-test.cc

Prepare for compilation with gcc (modules branch).

Re-enable module testing

---

include/fmt/core.h
include/fmt/format.h
test/CMakeLists.txt
test/static-export-test/CMakeLists.txt
test/static-export-test/library.cc
test/static-export-test/main.cc

If static fmt library is used in shared library.
Error in commit 13e652939b222249073281e507848e3db9fa3e65.

Fix "undefined reference to `fmt::v7::detail::basic_data<void>::digits'"

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Few points for this PR, as usual:
* I use `--parallel` option of `cmake --build` subcommand to pass threads count in a cross-compile way, it's available with CMake 3.12+, [all containers](https://github.com/actions/virtual-environments#available-environments) of GitHub Actions have 3.20+
* each platform use different approaches to get the number of threads:
* `nproc` for Linux, returns `2`
* `sysctl -n hw.logicalcpu` for macOS, since there is no `nproc`, returns `3`
* `(Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors` for Windows, returns `2`
of course, these values could be hardcoded according to [Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), …

CI: set up multi-thread build for all platforms

---

include/fmt/format.h

We are shifting past 32 bit since the integer literals are 32 bits wide.
Additionally, it looks like having the constexpr table inside the function leads to [pretty bad codegen on MSVC](https://godbolt.org/z/sYzqbE4zr), so it might make sense to [move it outside the function](https://godbolt.org/z/4cv4xMoxr), though I didn't include that here since I don't know how you deal with constexpr globals

Fix MSVC Win32 count_digits

---

include/fmt/format.h

Fixed compile error when trying to format a range with a value type formattable only to wide strings.

Fixed join_view formatter for wchar_t

---

test/chrono-test.cc

The weekday can be three chars long:
```
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
Чтв Июн 10 23:45:13 YEKT 2021
```

Fix chrono_test.weekday on legacy glibc

---

.github/workflows/linux.yml
include/fmt/chrono.h

Partial fix for issue https://github.com/fmtlib/fmt/issues/2337#issuecomment-854962103 on libc++.
locale: ja_JP.utf8
See: https://datatracker.ietf.org/doc/html/rfc3629

Fix chrono_test.locale on libc++

---

include/fmt/core.h
include/fmt/os.h
test/CMakeLists.txt

Do this  in _some_ tests to improve test coverage and catch possible problems due to that.

Instruct msvc to report the true value in `__cplusplus`

---

CMakeLists.txt

CMake: 3.15.4
Master project cmake output:
```
-- Version: 7.1.4
```
Tests output:
```Start 20: add-subdirectory-test``` (cmake output):
```
20: Version: 7.1.4
```
```Start 21: static-export-test``` (cmake output):
```
21: Version: TRUE7.1.4
```

Fix bug in cmake join function

---

include/fmt/core.h

The intel compiler defines `__GNUC__`, but does not support the gcc `_Pragma`.  This PR filters out the intel compiler to avoid warnings about an unrecognized function.

Eliminate intel compiler warning

---

include/fmt/format.h

The udl_{arg,formatter} structs are only defined when `FMT_USE_USER_DEFINED_LITERALS` is set, so don't try to define things that return that struct when it's not defined.
Fixes https://bugs.gentoo.org/797406

format: do not use udl_{arg,formatter} return types when UDL is not in use

---

include/fmt/format.h

This fixes issue #2386 by working around [GCC bug #66921](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66921) in GCC 4.9.2.
#2216 actually already specified the size of the `prefixes` data member, so this just explicitly specifies the sizes for the other members initialized with an initializer list as well.

Specify more sizes for static data, fix #2386

---

include/fmt/core.h

This PR implements the changes proposed in issue #2368.

PR followup for os.h false linter errors
